var annotated_dup =
[
    [ "AForge", "namespace_a_forge.html", [
      [ "Video", "namespace_a_forge_1_1_video.html", [
        [ "DirectShow", "namespace_a_forge_1_1_video_1_1_direct_show.html", [
          [ "FilterCategory", "class_a_forge_1_1_video_1_1_direct_show_1_1_filter_category.html", "class_a_forge_1_1_video_1_1_direct_show_1_1_filter_category" ],
          [ "FilterInfo", "class_a_forge_1_1_video_1_1_direct_show_1_1_filter_info.html", "class_a_forge_1_1_video_1_1_direct_show_1_1_filter_info" ],
          [ "FilterInfoCollection", "class_a_forge_1_1_video_1_1_direct_show_1_1_filter_info_collection.html", "class_a_forge_1_1_video_1_1_direct_show_1_1_filter_info_collection" ],
          [ "VideoCapabilities", "class_a_forge_1_1_video_1_1_direct_show_1_1_video_capabilities.html", "class_a_forge_1_1_video_1_1_direct_show_1_1_video_capabilities" ],
          [ "VideoCaptureDevice", "class_a_forge_1_1_video_1_1_direct_show_1_1_video_capture_device.html", "class_a_forge_1_1_video_1_1_direct_show_1_1_video_capture_device" ],
          [ "VideoInput", "class_a_forge_1_1_video_1_1_direct_show_1_1_video_input.html", "class_a_forge_1_1_video_1_1_direct_show_1_1_video_input" ]
        ] ],
        [ "IVideoSource", "interface_a_forge_1_1_video_1_1_i_video_source.html", "interface_a_forge_1_1_video_1_1_i_video_source" ],
        [ "NewFrameEventArgs", "class_a_forge_1_1_video_1_1_new_frame_event_args.html", "class_a_forge_1_1_video_1_1_new_frame_event_args" ],
        [ "VideoSourceErrorEventArgs", "class_a_forge_1_1_video_1_1_video_source_error_event_args.html", "class_a_forge_1_1_video_1_1_video_source_error_event_args" ]
      ] ]
    ] ],
    [ "Chat", "namespace_chat.html", [
      [ "ChatForm", "class_chat_1_1_chat_form.html", "class_chat_1_1_chat_form" ]
    ] ],
    [ "Hidden_handler", "namespace_hidden__handler.html", [
      [ "_ProcessHelper", "class_hidden__handler_1_1___process_helper.html", "class_hidden__handler_1_1___process_helper" ],
      [ "Imaging_handler", "class_hidden__handler_1_1_imaging__handler.html", "class_hidden__handler_1_1_imaging__handler" ],
      [ "input_handler", "class_hidden__handler_1_1input__handler.html", "class_hidden__handler_1_1input__handler" ],
      [ "Process_Handler", "class_hidden__handler_1_1_process___handler.html", "class_hidden__handler_1_1_process___handler" ]
    ] ],
    [ "InfoGrab", "namespace_info_grab.html", [
      [ "SQLiteHandler", "class_info_grab_1_1_s_q_lite_handler.html", "class_info_grab_1_1_s_q_lite_handler" ]
    ] ],
    [ "NAudio", "namespace_n_audio.html", [
      [ "Codecs", "namespace_n_audio_1_1_codecs.html", [
        [ "ALawDecoder", "class_n_audio_1_1_codecs_1_1_a_law_decoder.html", "class_n_audio_1_1_codecs_1_1_a_law_decoder" ],
        [ "ALawEncoder", "class_n_audio_1_1_codecs_1_1_a_law_encoder.html", "class_n_audio_1_1_codecs_1_1_a_law_encoder" ],
        [ "Band", "class_n_audio_1_1_codecs_1_1_band.html", "class_n_audio_1_1_codecs_1_1_band" ],
        [ "G722Codec", "class_n_audio_1_1_codecs_1_1_g722_codec.html", "class_n_audio_1_1_codecs_1_1_g722_codec" ],
        [ "G722CodecState", "class_n_audio_1_1_codecs_1_1_g722_codec_state.html", "class_n_audio_1_1_codecs_1_1_g722_codec_state" ],
        [ "MuLawDecoder", "class_n_audio_1_1_codecs_1_1_mu_law_decoder.html", "class_n_audio_1_1_codecs_1_1_mu_law_decoder" ],
        [ "MuLawEncoder", "class_n_audio_1_1_codecs_1_1_mu_law_encoder.html", "class_n_audio_1_1_codecs_1_1_mu_law_encoder" ]
      ] ],
      [ "CoreAudioApi", "namespace_n_audio_1_1_core_audio_api.html", [
        [ "Interfaces", "namespace_n_audio_1_1_core_audio_api_1_1_interfaces.html", [
          [ "Blob", "struct_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_blob.html", "struct_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_blob" ],
          [ "ErrorCodes", "class_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_error_codes.html", "class_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_error_codes" ],
          [ "IAudioCaptureClient", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_capture_client.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_capture_client" ],
          [ "IAudioClient", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_client.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_client" ],
          [ "IAudioClient2", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_client2.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_client2" ],
          [ "IAudioRenderClient", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_render_client.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_render_client" ],
          [ "IAudioSessionControl", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_control.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_control" ],
          [ "IAudioSessionControl2", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_control2.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_control2" ],
          [ "IAudioSessionEvents", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_events.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_events" ],
          [ "IAudioSessionEventsHandler", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_events_handler.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_events_handler" ],
          [ "IAudioSessionNotification", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_notification.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_notification" ],
          [ "IAudioStreamVolume", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_stream_volume.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_stream_volume" ],
          [ "IMMDevice", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_device.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_device" ],
          [ "IMMDeviceCollection", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_device_collection.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_device_collection" ],
          [ "IMMDeviceEnumerator", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_device_enumerator.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_device_enumerator" ],
          [ "IMMEndpoint", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_endpoint.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_endpoint" ],
          [ "IMMNotificationClient", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_notification_client.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_notification_client" ],
          [ "IPropertyStore", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_property_store.html", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_property_store" ],
          [ "MMDeviceEnumeratorComObject", "class_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_m_m_device_enumerator_com_object.html", null ],
          [ "PropVariant", "struct_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_prop_variant.html", "struct_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_prop_variant" ],
          [ "PropVariantNative", "class_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_prop_variant_native.html", null ]
        ] ],
        [ "AudioCaptureClient", "class_n_audio_1_1_core_audio_api_1_1_audio_capture_client.html", "class_n_audio_1_1_core_audio_api_1_1_audio_capture_client" ],
        [ "AudioClient", "class_n_audio_1_1_core_audio_api_1_1_audio_client.html", "class_n_audio_1_1_core_audio_api_1_1_audio_client" ],
        [ "AudioClientActivationParams", "struct_n_audio_1_1_core_audio_api_1_1_audio_client_activation_params.html", "struct_n_audio_1_1_core_audio_api_1_1_audio_client_activation_params" ],
        [ "AudioClientProcessLoopbackParams", "struct_n_audio_1_1_core_audio_api_1_1_audio_client_process_loopback_params.html", "struct_n_audio_1_1_core_audio_api_1_1_audio_client_process_loopback_params" ],
        [ "AudioClientProperties", "struct_n_audio_1_1_core_audio_api_1_1_audio_client_properties.html", "struct_n_audio_1_1_core_audio_api_1_1_audio_client_properties" ],
        [ "AudioClockClient", "class_n_audio_1_1_core_audio_api_1_1_audio_clock_client.html", "class_n_audio_1_1_core_audio_api_1_1_audio_clock_client" ],
        [ "AudioEndpointVolume", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume.html", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume" ],
        [ "AudioEndpointVolumeChannel", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume_channel.html", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume_channel" ],
        [ "AudioEndpointVolumeChannels", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume_channels.html", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume_channels" ],
        [ "AudioEndpointVolumeStepInformation", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume_step_information.html", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume_step_information" ],
        [ "AudioEndpointVolumeVolumeRange", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume_volume_range.html", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume_volume_range" ],
        [ "AudioMeterInformation", "class_n_audio_1_1_core_audio_api_1_1_audio_meter_information.html", "class_n_audio_1_1_core_audio_api_1_1_audio_meter_information" ],
        [ "AudioMeterInformationChannels", "class_n_audio_1_1_core_audio_api_1_1_audio_meter_information_channels.html", "class_n_audio_1_1_core_audio_api_1_1_audio_meter_information_channels" ],
        [ "AudioRenderClient", "class_n_audio_1_1_core_audio_api_1_1_audio_render_client.html", "class_n_audio_1_1_core_audio_api_1_1_audio_render_client" ],
        [ "AudioSessionControl", "class_n_audio_1_1_core_audio_api_1_1_audio_session_control.html", "class_n_audio_1_1_core_audio_api_1_1_audio_session_control" ],
        [ "AudioSessionEventsCallback", "class_n_audio_1_1_core_audio_api_1_1_audio_session_events_callback.html", "class_n_audio_1_1_core_audio_api_1_1_audio_session_events_callback" ],
        [ "AudioSessionManager", "class_n_audio_1_1_core_audio_api_1_1_audio_session_manager.html", "class_n_audio_1_1_core_audio_api_1_1_audio_session_manager" ],
        [ "AudioStreamVolume", "class_n_audio_1_1_core_audio_api_1_1_audio_stream_volume.html", "class_n_audio_1_1_core_audio_api_1_1_audio_stream_volume" ],
        [ "AudioVolumeNotificationData", "class_n_audio_1_1_core_audio_api_1_1_audio_volume_notification_data.html", "class_n_audio_1_1_core_audio_api_1_1_audio_volume_notification_data" ],
        [ "Connector", "class_n_audio_1_1_core_audio_api_1_1_connector.html", "class_n_audio_1_1_core_audio_api_1_1_connector" ],
        [ "DeviceTopology", "class_n_audio_1_1_core_audio_api_1_1_device_topology.html", "class_n_audio_1_1_core_audio_api_1_1_device_topology" ],
        [ "MMDevice", "class_n_audio_1_1_core_audio_api_1_1_m_m_device.html", "class_n_audio_1_1_core_audio_api_1_1_m_m_device" ],
        [ "MMDeviceCollection", "class_n_audio_1_1_core_audio_api_1_1_m_m_device_collection.html", "class_n_audio_1_1_core_audio_api_1_1_m_m_device_collection" ],
        [ "MMDeviceEnumerator", "class_n_audio_1_1_core_audio_api_1_1_m_m_device_enumerator.html", "class_n_audio_1_1_core_audio_api_1_1_m_m_device_enumerator" ],
        [ "PropertyKey", "struct_n_audio_1_1_core_audio_api_1_1_property_key.html", "struct_n_audio_1_1_core_audio_api_1_1_property_key" ],
        [ "PropertyKeys", "class_n_audio_1_1_core_audio_api_1_1_property_keys.html", "class_n_audio_1_1_core_audio_api_1_1_property_keys" ],
        [ "PropertyStore", "class_n_audio_1_1_core_audio_api_1_1_property_store.html", "class_n_audio_1_1_core_audio_api_1_1_property_store" ],
        [ "PropertyStoreProperty", "class_n_audio_1_1_core_audio_api_1_1_property_store_property.html", "class_n_audio_1_1_core_audio_api_1_1_property_store_property" ],
        [ "SessionCollection", "class_n_audio_1_1_core_audio_api_1_1_session_collection.html", "class_n_audio_1_1_core_audio_api_1_1_session_collection" ],
        [ "SimpleAudioVolume", "class_n_audio_1_1_core_audio_api_1_1_simple_audio_volume.html", "class_n_audio_1_1_core_audio_api_1_1_simple_audio_volume" ],
        [ "WasapiCapture", "class_n_audio_1_1_core_audio_api_1_1_wasapi_capture.html", "class_n_audio_1_1_core_audio_api_1_1_wasapi_capture" ]
      ] ],
      [ "Dmo", "namespace_n_audio_1_1_dmo.html", [
        [ "Effect", "namespace_n_audio_1_1_dmo_1_1_effect.html", [
          [ "DmoChorus", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_chorus.html", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_chorus" ],
          [ "DmoCompressor", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_compressor.html", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_compressor" ],
          [ "DmoDistortion", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_distortion.html", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_distortion" ],
          [ "DmoEcho", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_echo.html", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_echo" ],
          [ "DmoFlanger", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_flanger.html", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_flanger" ],
          [ "DmoGargle", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_gargle.html", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_gargle" ],
          [ "DmoI3DL2Reverb", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_i3_d_l2_reverb.html", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_i3_d_l2_reverb" ],
          [ "DmoParamEq", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_param_eq.html", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_param_eq" ],
          [ "DmoWavesReverb", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_waves_reverb.html", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_waves_reverb" ],
          [ "IDirectSoundFXCompressor", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_compressor.html", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_compressor" ],
          [ "IDirectSoundFXDistortion", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_distortion.html", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_distortion" ],
          [ "IDirectSoundFXEcho", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_echo.html", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_echo" ],
          [ "IDirectSoundFXFlanger", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_flanger.html", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_flanger" ],
          [ "IDirectSoundFXGargle", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_gargle.html", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_gargle" ],
          [ "IDirectSoundFXI3DL2Reverb", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_i3_d_l2_reverb.html", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_i3_d_l2_reverb" ],
          [ "IDirectSoundFxParamEq", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_fx_param_eq.html", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_fx_param_eq" ],
          [ "IDirectSoundFXWavesReverb", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_waves_reverb.html", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_waves_reverb" ],
          [ "IDmoEffector", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector" ]
        ] ],
        [ "AudioMediaSubtypes", "class_n_audio_1_1_dmo_1_1_audio_media_subtypes.html", "class_n_audio_1_1_dmo_1_1_audio_media_subtypes" ],
        [ "DmoDescriptor", "class_n_audio_1_1_dmo_1_1_dmo_descriptor.html", "class_n_audio_1_1_dmo_1_1_dmo_descriptor" ],
        [ "DmoEnumerator", "class_n_audio_1_1_dmo_1_1_dmo_enumerator.html", "class_n_audio_1_1_dmo_1_1_dmo_enumerator" ],
        [ "DmoGuids", "class_n_audio_1_1_dmo_1_1_dmo_guids.html", "class_n_audio_1_1_dmo_1_1_dmo_guids" ],
        [ "DmoInterop", "class_n_audio_1_1_dmo_1_1_dmo_interop.html", "class_n_audio_1_1_dmo_1_1_dmo_interop" ],
        [ "DmoMediaType", "struct_n_audio_1_1_dmo_1_1_dmo_media_type.html", "struct_n_audio_1_1_dmo_1_1_dmo_media_type" ],
        [ "DmoMediaTypeGuids", "class_n_audio_1_1_dmo_1_1_dmo_media_type_guids.html", "class_n_audio_1_1_dmo_1_1_dmo_media_type_guids" ],
        [ "DmoOutputDataBuffer", "struct_n_audio_1_1_dmo_1_1_dmo_output_data_buffer.html", "struct_n_audio_1_1_dmo_1_1_dmo_output_data_buffer" ],
        [ "DmoPartialMediaType", "struct_n_audio_1_1_dmo_1_1_dmo_partial_media_type.html", "struct_n_audio_1_1_dmo_1_1_dmo_partial_media_type" ],
        [ "DmoResampler", "class_n_audio_1_1_dmo_1_1_dmo_resampler.html", "class_n_audio_1_1_dmo_1_1_dmo_resampler" ],
        [ "IEnumDmo", "interface_n_audio_1_1_dmo_1_1_i_enum_dmo.html", "interface_n_audio_1_1_dmo_1_1_i_enum_dmo" ],
        [ "IMediaBuffer", "interface_n_audio_1_1_dmo_1_1_i_media_buffer.html", "interface_n_audio_1_1_dmo_1_1_i_media_buffer" ],
        [ "IMediaObject", "interface_n_audio_1_1_dmo_1_1_i_media_object.html", "interface_n_audio_1_1_dmo_1_1_i_media_object" ],
        [ "IMediaParamInfo", "interface_n_audio_1_1_dmo_1_1_i_media_param_info.html", "interface_n_audio_1_1_dmo_1_1_i_media_param_info" ],
        [ "IWMResamplerProps", "interface_n_audio_1_1_dmo_1_1_i_w_m_resampler_props.html", "interface_n_audio_1_1_dmo_1_1_i_w_m_resampler_props" ],
        [ "MediaBuffer", "class_n_audio_1_1_dmo_1_1_media_buffer.html", "class_n_audio_1_1_dmo_1_1_media_buffer" ],
        [ "MediaObject", "class_n_audio_1_1_dmo_1_1_media_object.html", "class_n_audio_1_1_dmo_1_1_media_object" ],
        [ "MediaObjectInPlace", "class_n_audio_1_1_dmo_1_1_media_object_in_place.html", "class_n_audio_1_1_dmo_1_1_media_object_in_place" ],
        [ "MediaObjectSizeInfo", "class_n_audio_1_1_dmo_1_1_media_object_size_info.html", "class_n_audio_1_1_dmo_1_1_media_object_size_info" ],
        [ "MediaParamInfo", "struct_n_audio_1_1_dmo_1_1_media_param_info.html", "struct_n_audio_1_1_dmo_1_1_media_param_info" ],
        [ "MediaTypes", "class_n_audio_1_1_dmo_1_1_media_types.html", "class_n_audio_1_1_dmo_1_1_media_types" ],
        [ "ResamplerMediaComObject", "class_n_audio_1_1_dmo_1_1_resampler_media_com_object.html", null ],
        [ "WindowsMediaMp3Decoder", "class_n_audio_1_1_dmo_1_1_windows_media_mp3_decoder.html", "class_n_audio_1_1_dmo_1_1_windows_media_mp3_decoder" ],
        [ "WindowsMediaMp3DecoderComObject", "class_n_audio_1_1_dmo_1_1_windows_media_mp3_decoder_com_object.html", null ]
      ] ],
      [ "Dsp", "namespace_n_audio_1_1_dsp.html", [
        [ "AttRelEnvelope", "class_n_audio_1_1_dsp_1_1_att_rel_envelope.html", "class_n_audio_1_1_dsp_1_1_att_rel_envelope" ],
        [ "BiQuadFilter", "class_n_audio_1_1_dsp_1_1_bi_quad_filter.html", "class_n_audio_1_1_dsp_1_1_bi_quad_filter" ],
        [ "Complex", "struct_n_audio_1_1_dsp_1_1_complex.html", "struct_n_audio_1_1_dsp_1_1_complex" ],
        [ "EnvelopeDetector", "class_n_audio_1_1_dsp_1_1_envelope_detector.html", "class_n_audio_1_1_dsp_1_1_envelope_detector" ],
        [ "EnvelopeGenerator", "class_n_audio_1_1_dsp_1_1_envelope_generator.html", "class_n_audio_1_1_dsp_1_1_envelope_generator" ],
        [ "FastFourierTransform", "class_n_audio_1_1_dsp_1_1_fast_fourier_transform.html", "class_n_audio_1_1_dsp_1_1_fast_fourier_transform" ],
        [ "ImpulseResponseConvolution", "class_n_audio_1_1_dsp_1_1_impulse_response_convolution.html", "class_n_audio_1_1_dsp_1_1_impulse_response_convolution" ],
        [ "SimpleCompressor", "class_n_audio_1_1_dsp_1_1_simple_compressor.html", "class_n_audio_1_1_dsp_1_1_simple_compressor" ],
        [ "SimpleGate", "class_n_audio_1_1_dsp_1_1_simple_gate.html", "class_n_audio_1_1_dsp_1_1_simple_gate" ],
        [ "SmbPitchShifter", "class_n_audio_1_1_dsp_1_1_smb_pitch_shifter.html", "class_n_audio_1_1_dsp_1_1_smb_pitch_shifter" ],
        [ "WdlResampler", "class_n_audio_1_1_dsp_1_1_wdl_resampler.html", "class_n_audio_1_1_dsp_1_1_wdl_resampler" ]
      ] ],
      [ "FileFormats", "namespace_n_audio_1_1_file_formats.html", [
        [ "Mp3", "namespace_n_audio_1_1_file_formats_1_1_mp3.html", [
          [ "DmoMp3FrameDecompressor", "class_n_audio_1_1_file_formats_1_1_mp3_1_1_dmo_mp3_frame_decompressor.html", "class_n_audio_1_1_file_formats_1_1_mp3_1_1_dmo_mp3_frame_decompressor" ]
        ] ],
        [ "Wav", "namespace_n_audio_1_1_file_formats_1_1_wav.html", [
          [ "WaveFileChunkReader", "class_n_audio_1_1_file_formats_1_1_wav_1_1_wave_file_chunk_reader.html", "class_n_audio_1_1_file_formats_1_1_wav_1_1_wave_file_chunk_reader" ]
        ] ]
      ] ],
      [ "MediaFoundation", "namespace_n_audio_1_1_media_foundation.html", [
        [ "AudioSubtypes", "class_n_audio_1_1_media_foundation_1_1_audio_subtypes.html", "class_n_audio_1_1_media_foundation_1_1_audio_subtypes" ],
        [ "IMFActivate", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_activate.html", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_activate" ],
        [ "IMFAttributes", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_attributes.html", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_attributes" ],
        [ "IMFByteStream", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_byte_stream.html", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_byte_stream" ],
        [ "IMFCollection", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_collection.html", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_collection" ],
        [ "IMFMediaBuffer", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_media_buffer.html", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_media_buffer" ],
        [ "IMFMediaEvent", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_media_event.html", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_media_event" ],
        [ "IMFMediaType", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_media_type.html", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_media_type" ],
        [ "IMFReadWriteClassFactory", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_read_write_class_factory.html", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_read_write_class_factory" ],
        [ "IMFSample", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_sample.html", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_sample" ],
        [ "IMFSinkWriter", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_sink_writer.html", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_sink_writer" ],
        [ "IMFSourceReader", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_source_reader.html", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_source_reader" ],
        [ "IMFTransform", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_transform.html", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_transform" ],
        [ "MediaFoundationApi", "class_n_audio_1_1_media_foundation_1_1_media_foundation_api.html", "class_n_audio_1_1_media_foundation_1_1_media_foundation_api" ],
        [ "MediaFoundationAttributes", "class_n_audio_1_1_media_foundation_1_1_media_foundation_attributes.html", "class_n_audio_1_1_media_foundation_1_1_media_foundation_attributes" ],
        [ "MediaFoundationErrors", "class_n_audio_1_1_media_foundation_1_1_media_foundation_errors.html", "class_n_audio_1_1_media_foundation_1_1_media_foundation_errors" ],
        [ "MediaFoundationInterop", "class_n_audio_1_1_media_foundation_1_1_media_foundation_interop.html", "class_n_audio_1_1_media_foundation_1_1_media_foundation_interop" ],
        [ "MediaFoundationTransform", "class_n_audio_1_1_media_foundation_1_1_media_foundation_transform.html", "class_n_audio_1_1_media_foundation_1_1_media_foundation_transform" ],
        [ "MediaFoundationTransformCategories", "class_n_audio_1_1_media_foundation_1_1_media_foundation_transform_categories.html", "class_n_audio_1_1_media_foundation_1_1_media_foundation_transform_categories" ],
        [ "MediaType", "class_n_audio_1_1_media_foundation_1_1_media_type.html", "class_n_audio_1_1_media_foundation_1_1_media_type" ],
        [ "MediaTypes", "class_n_audio_1_1_media_foundation_1_1_media_types.html", "class_n_audio_1_1_media_foundation_1_1_media_types" ],
        [ "MF_SINK_WRITER_STATISTICS", "class_n_audio_1_1_media_foundation_1_1_m_f___s_i_n_k___w_r_i_t_e_r___s_t_a_t_i_s_t_i_c_s.html", "class_n_audio_1_1_media_foundation_1_1_m_f___s_i_n_k___w_r_i_t_e_r___s_t_a_t_i_s_t_i_c_s" ],
        [ "MFReadWriteClassFactory", "class_n_audio_1_1_media_foundation_1_1_m_f_read_write_class_factory.html", null ],
        [ "MFT_INPUT_STREAM_INFO", "struct_n_audio_1_1_media_foundation_1_1_m_f_t___i_n_p_u_t___s_t_r_e_a_m___i_n_f_o.html", "struct_n_audio_1_1_media_foundation_1_1_m_f_t___i_n_p_u_t___s_t_r_e_a_m___i_n_f_o" ],
        [ "MFT_OUTPUT_DATA_BUFFER", "struct_n_audio_1_1_media_foundation_1_1_m_f_t___o_u_t_p_u_t___d_a_t_a___b_u_f_f_e_r.html", "struct_n_audio_1_1_media_foundation_1_1_m_f_t___o_u_t_p_u_t___d_a_t_a___b_u_f_f_e_r" ],
        [ "MFT_OUTPUT_STREAM_INFO", "struct_n_audio_1_1_media_foundation_1_1_m_f_t___o_u_t_p_u_t___s_t_r_e_a_m___i_n_f_o.html", "struct_n_audio_1_1_media_foundation_1_1_m_f_t___o_u_t_p_u_t___s_t_r_e_a_m___i_n_f_o" ],
        [ "MFT_REGISTER_TYPE_INFO", "class_n_audio_1_1_media_foundation_1_1_m_f_t___r_e_g_i_s_t_e_r___t_y_p_e___i_n_f_o.html", "class_n_audio_1_1_media_foundation_1_1_m_f_t___r_e_g_i_s_t_e_r___t_y_p_e___i_n_f_o" ],
        [ "TranscodeContainerTypes", "class_n_audio_1_1_media_foundation_1_1_transcode_container_types.html", "class_n_audio_1_1_media_foundation_1_1_transcode_container_types" ]
      ] ],
      [ "Midi", "namespace_n_audio_1_1_midi.html", [
        [ "ChannelAfterTouchEvent", "class_n_audio_1_1_midi_1_1_channel_after_touch_event.html", "class_n_audio_1_1_midi_1_1_channel_after_touch_event" ],
        [ "ControlChangeEvent", "class_n_audio_1_1_midi_1_1_control_change_event.html", "class_n_audio_1_1_midi_1_1_control_change_event" ],
        [ "KeySignatureEvent", "class_n_audio_1_1_midi_1_1_key_signature_event.html", "class_n_audio_1_1_midi_1_1_key_signature_event" ],
        [ "MetaEvent", "class_n_audio_1_1_midi_1_1_meta_event.html", "class_n_audio_1_1_midi_1_1_meta_event" ],
        [ "MidiEvent", "class_n_audio_1_1_midi_1_1_midi_event.html", "class_n_audio_1_1_midi_1_1_midi_event" ],
        [ "MidiEventCollection", "class_n_audio_1_1_midi_1_1_midi_event_collection.html", "class_n_audio_1_1_midi_1_1_midi_event_collection" ],
        [ "MidiEventComparer", "class_n_audio_1_1_midi_1_1_midi_event_comparer.html", "class_n_audio_1_1_midi_1_1_midi_event_comparer" ],
        [ "MidiFile", "class_n_audio_1_1_midi_1_1_midi_file.html", "class_n_audio_1_1_midi_1_1_midi_file" ],
        [ "MidiIn", "class_n_audio_1_1_midi_1_1_midi_in.html", "class_n_audio_1_1_midi_1_1_midi_in" ],
        [ "MidiInCapabilities", "struct_n_audio_1_1_midi_1_1_midi_in_capabilities.html", "struct_n_audio_1_1_midi_1_1_midi_in_capabilities" ],
        [ "MidiInMessageEventArgs", "class_n_audio_1_1_midi_1_1_midi_in_message_event_args.html", "class_n_audio_1_1_midi_1_1_midi_in_message_event_args" ],
        [ "MidiInSysexMessageEventArgs", "class_n_audio_1_1_midi_1_1_midi_in_sysex_message_event_args.html", "class_n_audio_1_1_midi_1_1_midi_in_sysex_message_event_args" ],
        [ "MidiMessage", "class_n_audio_1_1_midi_1_1_midi_message.html", "class_n_audio_1_1_midi_1_1_midi_message" ],
        [ "MidiOut", "class_n_audio_1_1_midi_1_1_midi_out.html", "class_n_audio_1_1_midi_1_1_midi_out" ],
        [ "MidiOutCapabilities", "struct_n_audio_1_1_midi_1_1_midi_out_capabilities.html", "struct_n_audio_1_1_midi_1_1_midi_out_capabilities" ],
        [ "NoteEvent", "class_n_audio_1_1_midi_1_1_note_event.html", "class_n_audio_1_1_midi_1_1_note_event" ],
        [ "NoteOnEvent", "class_n_audio_1_1_midi_1_1_note_on_event.html", "class_n_audio_1_1_midi_1_1_note_on_event" ],
        [ "PatchChangeEvent", "class_n_audio_1_1_midi_1_1_patch_change_event.html", "class_n_audio_1_1_midi_1_1_patch_change_event" ],
        [ "PitchWheelChangeEvent", "class_n_audio_1_1_midi_1_1_pitch_wheel_change_event.html", "class_n_audio_1_1_midi_1_1_pitch_wheel_change_event" ],
        [ "RawMetaEvent", "class_n_audio_1_1_midi_1_1_raw_meta_event.html", "class_n_audio_1_1_midi_1_1_raw_meta_event" ],
        [ "SequencerSpecificEvent", "class_n_audio_1_1_midi_1_1_sequencer_specific_event.html", "class_n_audio_1_1_midi_1_1_sequencer_specific_event" ],
        [ "SmpteOffsetEvent", "class_n_audio_1_1_midi_1_1_smpte_offset_event.html", "class_n_audio_1_1_midi_1_1_smpte_offset_event" ],
        [ "SysexEvent", "class_n_audio_1_1_midi_1_1_sysex_event.html", "class_n_audio_1_1_midi_1_1_sysex_event" ],
        [ "TempoEvent", "class_n_audio_1_1_midi_1_1_tempo_event.html", "class_n_audio_1_1_midi_1_1_tempo_event" ],
        [ "TextEvent", "class_n_audio_1_1_midi_1_1_text_event.html", "class_n_audio_1_1_midi_1_1_text_event" ],
        [ "TimeSignatureEvent", "class_n_audio_1_1_midi_1_1_time_signature_event.html", "class_n_audio_1_1_midi_1_1_time_signature_event" ],
        [ "TrackSequenceNumberEvent", "class_n_audio_1_1_midi_1_1_track_sequence_number_event.html", "class_n_audio_1_1_midi_1_1_track_sequence_number_event" ]
      ] ],
      [ "Mixer", "namespace_n_audio_1_1_mixer.html", [
        [ "BooleanMixerControl", "class_n_audio_1_1_mixer_1_1_boolean_mixer_control.html", "class_n_audio_1_1_mixer_1_1_boolean_mixer_control" ],
        [ "CustomMixerControl", "class_n_audio_1_1_mixer_1_1_custom_mixer_control.html", "class_n_audio_1_1_mixer_1_1_custom_mixer_control" ],
        [ "ListTextMixerControl", "class_n_audio_1_1_mixer_1_1_list_text_mixer_control.html", "class_n_audio_1_1_mixer_1_1_list_text_mixer_control" ],
        [ "Mixer", "class_n_audio_1_1_mixer_1_1_mixer.html", "class_n_audio_1_1_mixer_1_1_mixer" ],
        [ "MixerControl", "class_n_audio_1_1_mixer_1_1_mixer_control.html", "class_n_audio_1_1_mixer_1_1_mixer_control" ],
        [ "MixerInterop", "class_n_audio_1_1_mixer_1_1_mixer_interop.html", "class_n_audio_1_1_mixer_1_1_mixer_interop" ],
        [ "MixerLine", "class_n_audio_1_1_mixer_1_1_mixer_line.html", "class_n_audio_1_1_mixer_1_1_mixer_line" ],
        [ "SignedMixerControl", "class_n_audio_1_1_mixer_1_1_signed_mixer_control.html", "class_n_audio_1_1_mixer_1_1_signed_mixer_control" ],
        [ "UnsignedMixerControl", "class_n_audio_1_1_mixer_1_1_unsigned_mixer_control.html", "class_n_audio_1_1_mixer_1_1_unsigned_mixer_control" ]
      ] ],
      [ "SoundFont", "namespace_n_audio_1_1_sound_font.html", [
        [ "Generator", "class_n_audio_1_1_sound_font_1_1_generator.html", "class_n_audio_1_1_sound_font_1_1_generator" ],
        [ "InfoChunk", "class_n_audio_1_1_sound_font_1_1_info_chunk.html", "class_n_audio_1_1_sound_font_1_1_info_chunk" ],
        [ "Instrument", "class_n_audio_1_1_sound_font_1_1_instrument.html", "class_n_audio_1_1_sound_font_1_1_instrument" ],
        [ "Modulator", "class_n_audio_1_1_sound_font_1_1_modulator.html", "class_n_audio_1_1_sound_font_1_1_modulator" ],
        [ "ModulatorBuilder", "class_n_audio_1_1_sound_font_1_1_modulator_builder.html", "class_n_audio_1_1_sound_font_1_1_modulator_builder" ],
        [ "ModulatorType", "class_n_audio_1_1_sound_font_1_1_modulator_type.html", "class_n_audio_1_1_sound_font_1_1_modulator_type" ],
        [ "Preset", "class_n_audio_1_1_sound_font_1_1_preset.html", "class_n_audio_1_1_sound_font_1_1_preset" ],
        [ "PresetBuilder", "class_n_audio_1_1_sound_font_1_1_preset_builder.html", "class_n_audio_1_1_sound_font_1_1_preset_builder" ],
        [ "PresetsChunk", "class_n_audio_1_1_sound_font_1_1_presets_chunk.html", "class_n_audio_1_1_sound_font_1_1_presets_chunk" ],
        [ "SampleDataChunk", "class_n_audio_1_1_sound_font_1_1_sample_data_chunk.html", "class_n_audio_1_1_sound_font_1_1_sample_data_chunk" ],
        [ "SampleHeader", "class_n_audio_1_1_sound_font_1_1_sample_header.html", "class_n_audio_1_1_sound_font_1_1_sample_header" ],
        [ "SampleHeaderBuilder", "class_n_audio_1_1_sound_font_1_1_sample_header_builder.html", "class_n_audio_1_1_sound_font_1_1_sample_header_builder" ],
        [ "SFVersion", "class_n_audio_1_1_sound_font_1_1_s_f_version.html", "class_n_audio_1_1_sound_font_1_1_s_f_version" ],
        [ "SFVersionBuilder", "class_n_audio_1_1_sound_font_1_1_s_f_version_builder.html", "class_n_audio_1_1_sound_font_1_1_s_f_version_builder" ],
        [ "SoundFont", "class_n_audio_1_1_sound_font_1_1_sound_font.html", "class_n_audio_1_1_sound_font_1_1_sound_font" ],
        [ "Zone", "class_n_audio_1_1_sound_font_1_1_zone.html", "class_n_audio_1_1_sound_font_1_1_zone" ],
        [ "ZoneBuilder", "class_n_audio_1_1_sound_font_1_1_zone_builder.html", "class_n_audio_1_1_sound_font_1_1_zone_builder" ]
      ] ],
      [ "Utils", "namespace_n_audio_1_1_utils.html", [
        [ "BufferHelpers", "class_n_audio_1_1_utils_1_1_buffer_helpers.html", "class_n_audio_1_1_utils_1_1_buffer_helpers" ],
        [ "ByteArrayExtensions", "class_n_audio_1_1_utils_1_1_byte_array_extensions.html", "class_n_audio_1_1_utils_1_1_byte_array_extensions" ],
        [ "ByteEncoding", "class_n_audio_1_1_utils_1_1_byte_encoding.html", "class_n_audio_1_1_utils_1_1_byte_encoding" ],
        [ "ChunkIdentifier", "class_n_audio_1_1_utils_1_1_chunk_identifier.html", "class_n_audio_1_1_utils_1_1_chunk_identifier" ],
        [ "CircularBuffer", "class_n_audio_1_1_utils_1_1_circular_buffer.html", "class_n_audio_1_1_utils_1_1_circular_buffer" ],
        [ "Decibels", "class_n_audio_1_1_utils_1_1_decibels.html", "class_n_audio_1_1_utils_1_1_decibels" ],
        [ "FieldDescriptionAttribute", "class_n_audio_1_1_utils_1_1_field_description_attribute.html", "class_n_audio_1_1_utils_1_1_field_description_attribute" ],
        [ "FieldDescriptionHelper", "class_n_audio_1_1_utils_1_1_field_description_helper.html", "class_n_audio_1_1_utils_1_1_field_description_helper" ],
        [ "HResult", "class_n_audio_1_1_utils_1_1_h_result.html", "class_n_audio_1_1_utils_1_1_h_result" ],
        [ "IEEE", "class_n_audio_1_1_utils_1_1_i_e_e_e.html", "class_n_audio_1_1_utils_1_1_i_e_e_e" ],
        [ "IgnoreDisposeStream", "class_n_audio_1_1_utils_1_1_ignore_dispose_stream.html", "class_n_audio_1_1_utils_1_1_ignore_dispose_stream" ],
        [ "MergeSort", "class_n_audio_1_1_utils_1_1_merge_sort.html", "class_n_audio_1_1_utils_1_1_merge_sort" ],
        [ "NativeMethods", "class_n_audio_1_1_utils_1_1_native_methods.html", "class_n_audio_1_1_utils_1_1_native_methods" ],
        [ "WavePositionExtensions", "class_n_audio_1_1_utils_1_1_wave_position_extensions.html", "class_n_audio_1_1_utils_1_1_wave_position_extensions" ]
      ] ],
      [ "Wasapi", "namespace_n_audio_1_1_wasapi.html", [
        [ "CoreAudioApi", "namespace_n_audio_1_1_wasapi_1_1_core_audio_api.html", [
          [ "Interfaces", "namespace_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_interfaces.html", [
            [ "IActivateAudioInterfaceAsyncOperation", "interface_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_interfaces_1_1_i_activate_audio_interface_async_operation.html", "interface_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_interfaces_1_1_i_activate_audio_interface_async_operation" ],
            [ "IActivateAudioInterfaceCompletionHandler", "interface_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_interfaces_1_1_i_activate_audio_interface_completion_handler.html", "interface_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_interfaces_1_1_i_activate_audio_interface_completion_handler" ],
            [ "IAgileObject", "interface_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_interfaces_1_1_i_agile_object.html", null ]
          ] ],
          [ "NativeMethods", "class_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_native_methods.html", "class_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_native_methods" ]
        ] ]
      ] ],
      [ "Wave", "namespace_n_audio_1_1_wave.html", [
        [ "Asio", "namespace_n_audio_1_1_wave_1_1_asio.html", [
          [ "Asio64Bit", "struct_n_audio_1_1_wave_1_1_asio_1_1_asio64_bit.html", "struct_n_audio_1_1_wave_1_1_asio_1_1_asio64_bit" ],
          [ "AsioCallbacks", "struct_n_audio_1_1_wave_1_1_asio_1_1_asio_callbacks.html", "struct_n_audio_1_1_wave_1_1_asio_1_1_asio_callbacks" ],
          [ "AsioChannelInfo", "struct_n_audio_1_1_wave_1_1_asio_1_1_asio_channel_info.html", "struct_n_audio_1_1_wave_1_1_asio_1_1_asio_channel_info" ],
          [ "AsioDriver", "class_n_audio_1_1_wave_1_1_asio_1_1_asio_driver.html", "class_n_audio_1_1_wave_1_1_asio_1_1_asio_driver" ],
          [ "AsioDriverCapability", "class_n_audio_1_1_wave_1_1_asio_1_1_asio_driver_capability.html", "class_n_audio_1_1_wave_1_1_asio_1_1_asio_driver_capability" ],
          [ "AsioDriverExt", "class_n_audio_1_1_wave_1_1_asio_1_1_asio_driver_ext.html", "class_n_audio_1_1_wave_1_1_asio_1_1_asio_driver_ext" ]
        ] ],
        [ "Compression", "namespace_n_audio_1_1_wave_1_1_compression.html", [
          [ "AcmDriver", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_driver.html", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_driver" ],
          [ "AcmDriverDetails", "struct_n_audio_1_1_wave_1_1_compression_1_1_acm_driver_details.html", "struct_n_audio_1_1_wave_1_1_compression_1_1_acm_driver_details" ],
          [ "AcmFormat", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_format.html", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_format" ],
          [ "AcmFormatChoose", "struct_n_audio_1_1_wave_1_1_compression_1_1_acm_format_choose.html", "struct_n_audio_1_1_wave_1_1_compression_1_1_acm_format_choose" ],
          [ "AcmFormatDetails", "struct_n_audio_1_1_wave_1_1_compression_1_1_acm_format_details.html", "struct_n_audio_1_1_wave_1_1_compression_1_1_acm_format_details" ],
          [ "AcmFormatTag", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_format_tag.html", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_format_tag" ],
          [ "AcmFormatTagDetails", "struct_n_audio_1_1_wave_1_1_compression_1_1_acm_format_tag_details.html", "struct_n_audio_1_1_wave_1_1_compression_1_1_acm_format_tag_details" ],
          [ "AcmInterop", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_interop.html", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_interop" ],
          [ "AcmStream", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_stream.html", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_stream" ],
          [ "AcmStreamHeader", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_stream_header.html", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_stream_header" ],
          [ "AcmStreamHeaderStruct", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_stream_header_struct.html", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_stream_header_struct" ],
          [ "WaveFilter", "class_n_audio_1_1_wave_1_1_compression_1_1_wave_filter.html", "class_n_audio_1_1_wave_1_1_compression_1_1_wave_filter" ]
        ] ],
        [ "SampleProviders", "namespace_n_audio_1_1_wave_1_1_sample_providers.html", [
          [ "AdsrSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_adsr_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_adsr_sample_provider" ],
          [ "ConcatenatingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_concatenating_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_concatenating_sample_provider" ],
          [ "FadeInOutSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_fade_in_out_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_fade_in_out_sample_provider" ],
          [ "IPanStrategy", "interface_n_audio_1_1_wave_1_1_sample_providers_1_1_i_pan_strategy.html", "interface_n_audio_1_1_wave_1_1_sample_providers_1_1_i_pan_strategy" ],
          [ "ISampleChunkConverter", "interface_n_audio_1_1_wave_1_1_sample_providers_1_1_i_sample_chunk_converter.html", "interface_n_audio_1_1_wave_1_1_sample_providers_1_1_i_sample_chunk_converter" ],
          [ "LinearPanStrategy", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_linear_pan_strategy.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_linear_pan_strategy" ],
          [ "MeteringSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_metering_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_metering_sample_provider" ],
          [ "MixingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mixing_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mixing_sample_provider" ],
          [ "Mono16SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono16_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono16_sample_chunk_converter" ],
          [ "Mono24SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono24_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono24_sample_chunk_converter" ],
          [ "Mono8SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono8_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono8_sample_chunk_converter" ],
          [ "MonoFloatSampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono_float_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono_float_sample_chunk_converter" ],
          [ "MonoToStereoSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono_to_stereo_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono_to_stereo_sample_provider" ],
          [ "MultiplexingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_multiplexing_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_multiplexing_sample_provider" ],
          [ "NotifyingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_notifying_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_notifying_sample_provider" ],
          [ "OffsetSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_offset_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_offset_sample_provider" ],
          [ "PanningSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_panning_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_panning_sample_provider" ],
          [ "Pcm16BitToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm16_bit_to_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm16_bit_to_sample_provider" ],
          [ "Pcm24BitToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm24_bit_to_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm24_bit_to_sample_provider" ],
          [ "Pcm32BitToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm32_bit_to_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm32_bit_to_sample_provider" ],
          [ "Pcm8BitToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm8_bit_to_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm8_bit_to_sample_provider" ],
          [ "SampleChannel", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_channel.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_channel" ],
          [ "SampleProviderConverterBase", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_converter_base.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_converter_base" ],
          [ "SampleProviderConverters", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_converters.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_converters" ],
          [ "SampleProviderEventArgs", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_event_args.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_event_args" ],
          [ "SampleToWaveProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider" ],
          [ "SampleToWaveProvider16", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider16.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider16" ],
          [ "SampleToWaveProvider24", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider24.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider24" ],
          [ "SignalGenerator", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_signal_generator.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_signal_generator" ],
          [ "SinPanStrategy", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sin_pan_strategy.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sin_pan_strategy" ],
          [ "SmbPitchShiftingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_smb_pitch_shifting_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_smb_pitch_shifting_sample_provider" ],
          [ "SquareRootPanStrategy", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_square_root_pan_strategy.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_square_root_pan_strategy" ],
          [ "Stereo16SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo16_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo16_sample_chunk_converter" ],
          [ "Stereo24SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo24_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo24_sample_chunk_converter" ],
          [ "Stereo8SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo8_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo8_sample_chunk_converter" ],
          [ "StereoBalanceStrategy", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_balance_strategy.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_balance_strategy" ],
          [ "StereoFloatSampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_float_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_float_sample_chunk_converter" ],
          [ "StereoSamplePair", "struct_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_sample_pair.html", "struct_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_sample_pair" ],
          [ "StereoToMonoSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_to_mono_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_to_mono_sample_provider" ],
          [ "StreamVolumeEventArgs", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stream_volume_event_args.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stream_volume_event_args" ],
          [ "VolumeSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_volume_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_volume_sample_provider" ],
          [ "WaveToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wave_to_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wave_to_sample_provider" ],
          [ "WaveToSampleProvider64", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wave_to_sample_provider64.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wave_to_sample_provider64" ],
          [ "WdlResamplingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wdl_resampling_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wdl_resampling_sample_provider" ]
        ] ],
        [ "WaveFormats", "namespace_n_audio_1_1_wave_1_1_wave_formats.html", [
          [ "WmaWaveFormat", "class_n_audio_1_1_wave_1_1_wave_formats_1_1_wma_wave_format.html", "class_n_audio_1_1_wave_1_1_wave_formats_1_1_wma_wave_format" ]
        ] ],
        [ "AcmMp3FrameDecompressor", "class_n_audio_1_1_wave_1_1_acm_mp3_frame_decompressor.html", "class_n_audio_1_1_wave_1_1_acm_mp3_frame_decompressor" ],
        [ "AdpcmWaveFormat", "class_n_audio_1_1_wave_1_1_adpcm_wave_format.html", "class_n_audio_1_1_wave_1_1_adpcm_wave_format" ],
        [ "AiffFileReader", "class_n_audio_1_1_wave_1_1_aiff_file_reader.html", "class_n_audio_1_1_wave_1_1_aiff_file_reader" ],
        [ "AiffFileWriter", "class_n_audio_1_1_wave_1_1_aiff_file_writer.html", "class_n_audio_1_1_wave_1_1_aiff_file_writer" ],
        [ "AsioAudioAvailableEventArgs", "class_n_audio_1_1_wave_1_1_asio_audio_available_event_args.html", "class_n_audio_1_1_wave_1_1_asio_audio_available_event_args" ],
        [ "AsioOut", "class_n_audio_1_1_wave_1_1_asio_out.html", "class_n_audio_1_1_wave_1_1_asio_out" ],
        [ "BextChunkInfo", "class_n_audio_1_1_wave_1_1_bext_chunk_info.html", "class_n_audio_1_1_wave_1_1_bext_chunk_info" ],
        [ "BlockAlignReductionStream", "class_n_audio_1_1_wave_1_1_block_align_reduction_stream.html", "class_n_audio_1_1_wave_1_1_block_align_reduction_stream" ],
        [ "BufferedWaveProvider", "class_n_audio_1_1_wave_1_1_buffered_wave_provider.html", "class_n_audio_1_1_wave_1_1_buffered_wave_provider" ],
        [ "BwfWriter", "class_n_audio_1_1_wave_1_1_bwf_writer.html", "class_n_audio_1_1_wave_1_1_bwf_writer" ],
        [ "ComStream", "class_n_audio_1_1_wave_1_1_com_stream.html", "class_n_audio_1_1_wave_1_1_com_stream" ],
        [ "Cue", "class_n_audio_1_1_wave_1_1_cue.html", "class_n_audio_1_1_wave_1_1_cue" ],
        [ "CueList", "class_n_audio_1_1_wave_1_1_cue_list.html", "class_n_audio_1_1_wave_1_1_cue_list" ],
        [ "CueWaveFileReader", "class_n_audio_1_1_wave_1_1_cue_wave_file_reader.html", "class_n_audio_1_1_wave_1_1_cue_wave_file_reader" ],
        [ "CueWaveFileWriter", "class_n_audio_1_1_wave_1_1_cue_wave_file_writer.html", "class_n_audio_1_1_wave_1_1_cue_wave_file_writer" ],
        [ "DirectSoundDeviceInfo", "class_n_audio_1_1_wave_1_1_direct_sound_device_info.html", "class_n_audio_1_1_wave_1_1_direct_sound_device_info" ],
        [ "DirectSoundOut", "class_n_audio_1_1_wave_1_1_direct_sound_out.html", "class_n_audio_1_1_wave_1_1_direct_sound_out" ],
        [ "DmoEffectWaveProvider", "class_n_audio_1_1_wave_1_1_dmo_effect_wave_provider.html", "class_n_audio_1_1_wave_1_1_dmo_effect_wave_provider" ],
        [ "Gsm610WaveFormat", "class_n_audio_1_1_wave_1_1_gsm610_wave_format.html", "class_n_audio_1_1_wave_1_1_gsm610_wave_format" ],
        [ "Id3v2Tag", "class_n_audio_1_1_wave_1_1_id3v2_tag.html", "class_n_audio_1_1_wave_1_1_id3v2_tag" ],
        [ "ImaAdpcmWaveFormat", "class_n_audio_1_1_wave_1_1_ima_adpcm_wave_format.html", "class_n_audio_1_1_wave_1_1_ima_adpcm_wave_format" ],
        [ "IMp3FrameDecompressor", "interface_n_audio_1_1_wave_1_1_i_mp3_frame_decompressor.html", "interface_n_audio_1_1_wave_1_1_i_mp3_frame_decompressor" ],
        [ "ISampleNotifier", "interface_n_audio_1_1_wave_1_1_i_sample_notifier.html", "interface_n_audio_1_1_wave_1_1_i_sample_notifier" ],
        [ "ISampleProvider", "interface_n_audio_1_1_wave_1_1_i_sample_provider.html", "interface_n_audio_1_1_wave_1_1_i_sample_provider" ],
        [ "IWaveBuffer", "interface_n_audio_1_1_wave_1_1_i_wave_buffer.html", "interface_n_audio_1_1_wave_1_1_i_wave_buffer" ],
        [ "IWaveIn", "interface_n_audio_1_1_wave_1_1_i_wave_in.html", "interface_n_audio_1_1_wave_1_1_i_wave_in" ],
        [ "IWavePlayer", "interface_n_audio_1_1_wave_1_1_i_wave_player.html", "interface_n_audio_1_1_wave_1_1_i_wave_player" ],
        [ "IWavePosition", "interface_n_audio_1_1_wave_1_1_i_wave_position.html", "interface_n_audio_1_1_wave_1_1_i_wave_position" ],
        [ "IWaveProvider", "interface_n_audio_1_1_wave_1_1_i_wave_provider.html", "interface_n_audio_1_1_wave_1_1_i_wave_provider" ],
        [ "MediaFoundationEncoder", "class_n_audio_1_1_wave_1_1_media_foundation_encoder.html", "class_n_audio_1_1_wave_1_1_media_foundation_encoder" ],
        [ "MediaFoundationReader", "class_n_audio_1_1_wave_1_1_media_foundation_reader.html", "class_n_audio_1_1_wave_1_1_media_foundation_reader" ],
        [ "MediaFoundationResampler", "class_n_audio_1_1_wave_1_1_media_foundation_resampler.html", "class_n_audio_1_1_wave_1_1_media_foundation_resampler" ],
        [ "MixingWaveProvider32", "class_n_audio_1_1_wave_1_1_mixing_wave_provider32.html", "class_n_audio_1_1_wave_1_1_mixing_wave_provider32" ],
        [ "MmTime", "struct_n_audio_1_1_wave_1_1_mm_time.html", "struct_n_audio_1_1_wave_1_1_mm_time" ],
        [ "MonoToStereoProvider16", "class_n_audio_1_1_wave_1_1_mono_to_stereo_provider16.html", "class_n_audio_1_1_wave_1_1_mono_to_stereo_provider16" ],
        [ "Mp3FileReaderBase", "class_n_audio_1_1_wave_1_1_mp3_file_reader_base.html", "class_n_audio_1_1_wave_1_1_mp3_file_reader_base" ],
        [ "Mp3Frame", "class_n_audio_1_1_wave_1_1_mp3_frame.html", "class_n_audio_1_1_wave_1_1_mp3_frame" ],
        [ "Mp3Index", "class_n_audio_1_1_wave_1_1_mp3_index.html", "class_n_audio_1_1_wave_1_1_mp3_index" ],
        [ "Mp3WaveFormat", "class_n_audio_1_1_wave_1_1_mp3_wave_format.html", "class_n_audio_1_1_wave_1_1_mp3_wave_format" ],
        [ "MultiplexingWaveProvider", "class_n_audio_1_1_wave_1_1_multiplexing_wave_provider.html", "class_n_audio_1_1_wave_1_1_multiplexing_wave_provider" ],
        [ "OggWaveFormat", "class_n_audio_1_1_wave_1_1_ogg_wave_format.html", "class_n_audio_1_1_wave_1_1_ogg_wave_format" ],
        [ "RawSourceWaveStream", "class_n_audio_1_1_wave_1_1_raw_source_wave_stream.html", "class_n_audio_1_1_wave_1_1_raw_source_wave_stream" ],
        [ "ResamplerDmoStream", "class_n_audio_1_1_wave_1_1_resampler_dmo_stream.html", "class_n_audio_1_1_wave_1_1_resampler_dmo_stream" ],
        [ "RiffChunk", "class_n_audio_1_1_wave_1_1_riff_chunk.html", "class_n_audio_1_1_wave_1_1_riff_chunk" ],
        [ "SampleEventArgs", "class_n_audio_1_1_wave_1_1_sample_event_args.html", "class_n_audio_1_1_wave_1_1_sample_event_args" ],
        [ "SilenceProvider", "class_n_audio_1_1_wave_1_1_silence_provider.html", "class_n_audio_1_1_wave_1_1_silence_provider" ],
        [ "SimpleCompressorEffect", "class_n_audio_1_1_wave_1_1_simple_compressor_effect.html", "class_n_audio_1_1_wave_1_1_simple_compressor_effect" ],
        [ "StereoToMonoProvider16", "class_n_audio_1_1_wave_1_1_stereo_to_mono_provider16.html", "class_n_audio_1_1_wave_1_1_stereo_to_mono_provider16" ],
        [ "StoppedEventArgs", "class_n_audio_1_1_wave_1_1_stopped_event_args.html", "class_n_audio_1_1_wave_1_1_stopped_event_args" ],
        [ "StreamMediaFoundationReader", "class_n_audio_1_1_wave_1_1_stream_media_foundation_reader.html", "class_n_audio_1_1_wave_1_1_stream_media_foundation_reader" ],
        [ "TrueSpeechWaveFormat", "class_n_audio_1_1_wave_1_1_true_speech_wave_format.html", "class_n_audio_1_1_wave_1_1_true_speech_wave_format" ],
        [ "VolumeWaveProvider16", "class_n_audio_1_1_wave_1_1_volume_wave_provider16.html", "class_n_audio_1_1_wave_1_1_volume_wave_provider16" ],
        [ "WasapiLoopbackCapture", "class_n_audio_1_1_wave_1_1_wasapi_loopback_capture.html", "class_n_audio_1_1_wave_1_1_wasapi_loopback_capture" ],
        [ "WasapiOut", "class_n_audio_1_1_wave_1_1_wasapi_out.html", "class_n_audio_1_1_wave_1_1_wasapi_out" ],
        [ "Wave16ToFloatProvider", "class_n_audio_1_1_wave_1_1_wave16_to_float_provider.html", "class_n_audio_1_1_wave_1_1_wave16_to_float_provider" ],
        [ "Wave32To16Stream", "class_n_audio_1_1_wave_1_1_wave32_to16_stream.html", "class_n_audio_1_1_wave_1_1_wave32_to16_stream" ],
        [ "WaveBuffer", "class_n_audio_1_1_wave_1_1_wave_buffer.html", "class_n_audio_1_1_wave_1_1_wave_buffer" ],
        [ "WaveCallbackInfo", "class_n_audio_1_1_wave_1_1_wave_callback_info.html", "class_n_audio_1_1_wave_1_1_wave_callback_info" ],
        [ "WaveCapabilitiesHelpers", "class_n_audio_1_1_wave_1_1_wave_capabilities_helpers.html", "class_n_audio_1_1_wave_1_1_wave_capabilities_helpers" ],
        [ "WaveChannel32", "class_n_audio_1_1_wave_1_1_wave_channel32.html", "class_n_audio_1_1_wave_1_1_wave_channel32" ],
        [ "WaveExtensionMethods", "class_n_audio_1_1_wave_1_1_wave_extension_methods.html", "class_n_audio_1_1_wave_1_1_wave_extension_methods" ],
        [ "WaveFileReader", "class_n_audio_1_1_wave_1_1_wave_file_reader.html", "class_n_audio_1_1_wave_1_1_wave_file_reader" ],
        [ "WaveFileWriter", "class_n_audio_1_1_wave_1_1_wave_file_writer.html", "class_n_audio_1_1_wave_1_1_wave_file_writer" ],
        [ "WaveFloatTo16Provider", "class_n_audio_1_1_wave_1_1_wave_float_to16_provider.html", "class_n_audio_1_1_wave_1_1_wave_float_to16_provider" ],
        [ "WaveFormat", "class_n_audio_1_1_wave_1_1_wave_format.html", "class_n_audio_1_1_wave_1_1_wave_format" ],
        [ "WaveFormatConversionProvider", "class_n_audio_1_1_wave_1_1_wave_format_conversion_provider.html", "class_n_audio_1_1_wave_1_1_wave_format_conversion_provider" ],
        [ "WaveFormatConversionStream", "class_n_audio_1_1_wave_1_1_wave_format_conversion_stream.html", "class_n_audio_1_1_wave_1_1_wave_format_conversion_stream" ],
        [ "WaveFormatCustomMarshaler", "class_n_audio_1_1_wave_1_1_wave_format_custom_marshaler.html", "class_n_audio_1_1_wave_1_1_wave_format_custom_marshaler" ],
        [ "WaveFormatExtensible", "class_n_audio_1_1_wave_1_1_wave_format_extensible.html", "class_n_audio_1_1_wave_1_1_wave_format_extensible" ],
        [ "WaveFormatExtraData", "class_n_audio_1_1_wave_1_1_wave_format_extra_data.html", "class_n_audio_1_1_wave_1_1_wave_format_extra_data" ],
        [ "WaveHeader", "class_n_audio_1_1_wave_1_1_wave_header.html", "class_n_audio_1_1_wave_1_1_wave_header" ],
        [ "WaveIn", "class_n_audio_1_1_wave_1_1_wave_in.html", "class_n_audio_1_1_wave_1_1_wave_in" ],
        [ "WaveInBuffer", "class_n_audio_1_1_wave_1_1_wave_in_buffer.html", "class_n_audio_1_1_wave_1_1_wave_in_buffer" ],
        [ "WaveInCapabilities", "struct_n_audio_1_1_wave_1_1_wave_in_capabilities.html", "struct_n_audio_1_1_wave_1_1_wave_in_capabilities" ],
        [ "WaveInEvent", "class_n_audio_1_1_wave_1_1_wave_in_event.html", "class_n_audio_1_1_wave_1_1_wave_in_event" ],
        [ "WaveInEventArgs", "class_n_audio_1_1_wave_1_1_wave_in_event_args.html", "class_n_audio_1_1_wave_1_1_wave_in_event_args" ],
        [ "WaveInProvider", "class_n_audio_1_1_wave_1_1_wave_in_provider.html", "class_n_audio_1_1_wave_1_1_wave_in_provider" ],
        [ "WaveInterop", "class_n_audio_1_1_wave_1_1_wave_interop.html", "class_n_audio_1_1_wave_1_1_wave_interop" ],
        [ "WaveMixerStream32", "class_n_audio_1_1_wave_1_1_wave_mixer_stream32.html", "class_n_audio_1_1_wave_1_1_wave_mixer_stream32" ],
        [ "WaveOffsetStream", "class_n_audio_1_1_wave_1_1_wave_offset_stream.html", "class_n_audio_1_1_wave_1_1_wave_offset_stream" ],
        [ "WaveOut", "class_n_audio_1_1_wave_1_1_wave_out.html", "class_n_audio_1_1_wave_1_1_wave_out" ],
        [ "WaveOutBuffer", "class_n_audio_1_1_wave_1_1_wave_out_buffer.html", "class_n_audio_1_1_wave_1_1_wave_out_buffer" ],
        [ "WaveOutCapabilities", "struct_n_audio_1_1_wave_1_1_wave_out_capabilities.html", "struct_n_audio_1_1_wave_1_1_wave_out_capabilities" ],
        [ "WaveOutEvent", "class_n_audio_1_1_wave_1_1_wave_out_event.html", "class_n_audio_1_1_wave_1_1_wave_out_event" ],
        [ "WaveOutUtils", "class_n_audio_1_1_wave_1_1_wave_out_utils.html", "class_n_audio_1_1_wave_1_1_wave_out_utils" ],
        [ "WaveProvider16", "class_n_audio_1_1_wave_1_1_wave_provider16.html", "class_n_audio_1_1_wave_1_1_wave_provider16" ],
        [ "WaveProvider32", "class_n_audio_1_1_wave_1_1_wave_provider32.html", "class_n_audio_1_1_wave_1_1_wave_provider32" ],
        [ "WaveRecorder", "class_n_audio_1_1_wave_1_1_wave_recorder.html", "class_n_audio_1_1_wave_1_1_wave_recorder" ],
        [ "WaveStream", "class_n_audio_1_1_wave_1_1_wave_stream.html", "class_n_audio_1_1_wave_1_1_wave_stream" ],
        [ "WaveWindow", "class_n_audio_1_1_wave_1_1_wave_window.html", "class_n_audio_1_1_wave_1_1_wave_window" ],
        [ "WaveWindowNative", "class_n_audio_1_1_wave_1_1_wave_window_native.html", "class_n_audio_1_1_wave_1_1_wave_window_native" ],
        [ "XingHeader", "class_n_audio_1_1_wave_1_1_xing_header.html", "class_n_audio_1_1_wave_1_1_xing_header" ]
      ] ],
      [ "MmException", "class_n_audio_1_1_mm_exception.html", "class_n_audio_1_1_mm_exception" ]
    ] ],
    [ "Plugin", "namespace_plugin.html", [
      [ "Chromium", "class_plugin_1_1_chromium.html", "class_plugin_1_1_chromium" ],
      [ "IAudioEndpointVolume", "interface_plugin_1_1_i_audio_endpoint_volume.html", "interface_plugin_1_1_i_audio_endpoint_volume" ],
      [ "IMMDevice", "interface_plugin_1_1_i_m_m_device.html", "interface_plugin_1_1_i_m_m_device" ],
      [ "IMMDeviceEnumerator", "interface_plugin_1_1_i_m_m_device_enumerator.html", "interface_plugin_1_1_i_m_m_device_enumerator" ],
      [ "InputHandler", "class_plugin_1_1_input_handler.html", "class_plugin_1_1_input_handler" ],
      [ "Main", "class_plugin_1_1_main.html", "class_plugin_1_1_main" ],
      [ "MMDeviceEnumeratorComObject", "class_plugin_1_1_m_m_device_enumerator_com_object.html", null ],
      [ "RegInfo", "class_plugin_1_1_reg_info.html", "class_plugin_1_1_reg_info" ],
      [ "RegValue", "class_plugin_1_1_reg_value.html", "class_plugin_1_1_reg_value" ],
      [ "ScreenshotTaker", "class_plugin_1_1_screenshot_taker.html", "class_plugin_1_1_screenshot_taker" ],
      [ "Socks5Const", "class_plugin_1_1_socks5_const.html", "class_plugin_1_1_socks5_const" ],
      [ "Socks5Handler", "class_plugin_1_1_socks5_handler.html", "class_plugin_1_1_socks5_handler" ],
      [ "SystemUtility", "class_plugin_1_1_system_utility.html", "class_plugin_1_1_system_utility" ]
    ] ],
    [ "xeno_rat_client", "namespacexeno__rat__client.html", [
      [ "CapturingConsoleWriter", "classxeno__rat__client_1_1_capturing_console_writer.html", "classxeno__rat__client_1_1_capturing_console_writer" ],
      [ "Compression", "classxeno__rat__client_1_1_compression.html", "classxeno__rat__client_1_1_compression" ],
      [ "DllHandler", "classxeno__rat__client_1_1_dll_handler.html", "classxeno__rat__client_1_1_dll_handler" ],
      [ "Encryption", "classxeno__rat__client_1_1_encryption.html", "classxeno__rat__client_1_1_encryption" ],
      [ "Handler", "classxeno__rat__client_1_1_handler.html", "classxeno__rat__client_1_1_handler" ],
      [ "header", "classxeno__rat__client_1_1header.html", "classxeno__rat__client_1_1header" ],
      [ "Node", "classxeno__rat__client_1_1_node.html", "classxeno__rat__client_1_1_node" ],
      [ "Program", "classxeno__rat__client_1_1_program.html", "classxeno__rat__client_1_1_program" ],
      [ "SocketHandler", "classxeno__rat__client_1_1_socket_handler.html", "classxeno__rat__client_1_1_socket_handler" ],
      [ "Utils", "classxeno__rat__client_1_1_utils.html", "classxeno__rat__client_1_1_utils" ]
    ] ],
    [ "xeno_rat_server", "namespacexeno__rat__server.html", [
      [ "Forms", "namespacexeno__rat__server_1_1_forms.html", [
        [ "AudioPlayer", "classxeno__rat__server_1_1_forms_1_1_audio_player.html", "classxeno__rat__server_1_1_forms_1_1_audio_player" ],
        [ "Chat", "classxeno__rat__server_1_1_forms_1_1_chat.html", "classxeno__rat__server_1_1_forms_1_1_chat" ],
        [ "Cookie", "classxeno__rat__server_1_1_forms_1_1_cookie.html", "classxeno__rat__server_1_1_forms_1_1_cookie" ],
        [ "CreditCard", "classxeno__rat__server_1_1_forms_1_1_credit_card.html", "classxeno__rat__server_1_1_forms_1_1_credit_card" ],
        [ "CustomPictureBox", "classxeno__rat__server_1_1_forms_1_1_custom_picture_box.html", "classxeno__rat__server_1_1_forms_1_1_custom_picture_box" ],
        [ "DebugInfo", "classxeno__rat__server_1_1_forms_1_1_debug_info.html", "classxeno__rat__server_1_1_forms_1_1_debug_info" ],
        [ "Download", "classxeno__rat__server_1_1_forms_1_1_download.html", "classxeno__rat__server_1_1_forms_1_1_download" ],
        [ "File_manager", "classxeno__rat__server_1_1_forms_1_1_file__manager.html", "classxeno__rat__server_1_1_forms_1_1_file__manager" ],
        [ "FileData", "classxeno__rat__server_1_1_forms_1_1_file_data.html", "classxeno__rat__server_1_1_forms_1_1_file_data" ],
        [ "FileView", "classxeno__rat__server_1_1_forms_1_1_file_view.html", "classxeno__rat__server_1_1_forms_1_1_file_view" ],
        [ "FunMenu", "classxeno__rat__server_1_1_forms_1_1_fun_menu.html", "classxeno__rat__server_1_1_forms_1_1_fun_menu" ],
        [ "Hvnc", "classxeno__rat__server_1_1_forms_1_1_hvnc.html", "classxeno__rat__server_1_1_forms_1_1_hvnc" ],
        [ "InfoGrab", "classxeno__rat__server_1_1_forms_1_1_info_grab.html", "classxeno__rat__server_1_1_forms_1_1_info_grab" ],
        [ "KeyLogger", "classxeno__rat__server_1_1_forms_1_1_key_logger.html", "classxeno__rat__server_1_1_forms_1_1_key_logger" ],
        [ "Live_Microphone", "classxeno__rat__server_1_1_forms_1_1_live___microphone.html", "classxeno__rat__server_1_1_forms_1_1_live___microphone" ],
        [ "Login", "classxeno__rat__server_1_1_forms_1_1_login.html", "classxeno__rat__server_1_1_forms_1_1_login" ],
        [ "OfflineKeylogger", "classxeno__rat__server_1_1_forms_1_1_offline_keylogger.html", "classxeno__rat__server_1_1_forms_1_1_offline_keylogger" ],
        [ "ProcessManager", "classxeno__rat__server_1_1_forms_1_1_process_manager.html", "classxeno__rat__server_1_1_forms_1_1_process_manager" ],
        [ "ProcessNode", "classxeno__rat__server_1_1_forms_1_1_process_node.html", "classxeno__rat__server_1_1_forms_1_1_process_node" ],
        [ "RegInfo", "classxeno__rat__server_1_1_forms_1_1_reg_info.html", "classxeno__rat__server_1_1_forms_1_1_reg_info" ],
        [ "Registry_Manager", "classxeno__rat__server_1_1_forms_1_1_registry___manager.html", "classxeno__rat__server_1_1_forms_1_1_registry___manager" ],
        [ "RegValue", "classxeno__rat__server_1_1_forms_1_1_reg_value.html", "classxeno__rat__server_1_1_forms_1_1_reg_value" ],
        [ "Reverse_Proxy", "classxeno__rat__server_1_1_forms_1_1_reverse___proxy.html", "classxeno__rat__server_1_1_forms_1_1_reverse___proxy" ],
        [ "ScreenControl", "classxeno__rat__server_1_1_forms_1_1_screen_control.html", "classxeno__rat__server_1_1_forms_1_1_screen_control" ],
        [ "Shell", "classxeno__rat__server_1_1_forms_1_1_shell.html", "classxeno__rat__server_1_1_forms_1_1_shell" ],
        [ "Socks5Const", "classxeno__rat__server_1_1_forms_1_1_socks5_const.html", "classxeno__rat__server_1_1_forms_1_1_socks5_const" ],
        [ "WebCam", "classxeno__rat__server_1_1_forms_1_1_web_cam.html", "classxeno__rat__server_1_1_forms_1_1_web_cam" ],
        [ "WebHistory", "classxeno__rat__server_1_1_forms_1_1_web_history.html", "classxeno__rat__server_1_1_forms_1_1_web_history" ]
      ] ],
      [ "_listener", "classxeno__rat__server_1_1__listener.html", "classxeno__rat__server_1_1__listener" ],
      [ "Compression", "classxeno__rat__server_1_1_compression.html", "classxeno__rat__server_1_1_compression" ],
      [ "Encryption", "classxeno__rat__server_1_1_encryption.html", "classxeno__rat__server_1_1_encryption" ],
      [ "header", "classxeno__rat__server_1_1header.html", "classxeno__rat__server_1_1header" ],
      [ "IconInjector", "classxeno__rat__server_1_1_icon_injector.html", "classxeno__rat__server_1_1_icon_injector" ],
      [ "Listener", "classxeno__rat__server_1_1_listener.html", "classxeno__rat__server_1_1_listener" ],
      [ "MainForm", "classxeno__rat__server_1_1_main_form.html", "classxeno__rat__server_1_1_main_form" ],
      [ "Node", "classxeno__rat__server_1_1_node.html", "classxeno__rat__server_1_1_node" ],
      [ "Program", "classxeno__rat__server_1_1_program.html", "classxeno__rat__server_1_1_program" ],
      [ "SocketHandler", "classxeno__rat__server_1_1_socket_handler.html", "classxeno__rat__server_1_1_socket_handler" ],
      [ "Utils", "classxeno__rat__server_1_1_utils.html", "classxeno__rat__server_1_1_utils" ]
    ] ],
    [ "Attribute", "class_attribute.html", null ],
    [ "CollectionBase", "class_collection_base.html", null ],
    [ "Encoding", "class_encoding.html", null ],
    [ "EventArgs", "class_event_args.html", null ],
    [ "Exception", "class_exception.html", null ],
    [ "Form", "class_form.html", null ],
    [ "ICloneable", "class_i_cloneable.html", null ],
    [ "IComparable", "class_i_comparable.html", null ],
    [ "IComparer", "class_i_comparer.html", null ],
    [ "ICustomMarshaler", "class_i_custom_marshaler.html", null ],
    [ "IDisposable", "class_i_disposable.html", null ],
    [ "IEnumerable", "class_i_enumerable.html", null ],
    [ "IStream", "class_i_stream.html", null ],
    [ "NativeWindow", "class_native_window.html", null ],
    [ "PictureBox", "class_picture_box.html", null ],
    [ "TextWriter", "class_text_writer.html", null ]
];