var dir_0c2bf4549f290cd74d246d82b479713d =
[
    [ "ChannelAfterTouchEvent.cs", "_channel_after_touch_event_8cs.html", "_channel_after_touch_event_8cs" ],
    [ "ControlChangeEvent.cs", "_control_change_event_8cs.html", "_control_change_event_8cs" ],
    [ "KeySignatureEvent.cs", "_key_signature_event_8cs.html", "_key_signature_event_8cs" ],
    [ "MetaEvent.cs", "_meta_event_8cs.html", "_meta_event_8cs" ],
    [ "MetaEventType.cs", "_meta_event_type_8cs.html", "_meta_event_type_8cs" ],
    [ "MidiCommandCode.cs", "_midi_command_code_8cs.html", "_midi_command_code_8cs" ],
    [ "MidiController.cs", "_midi_controller_8cs.html", "_midi_controller_8cs" ],
    [ "MidiEvent.cs", "_midi_event_8cs.html", "_midi_event_8cs" ],
    [ "MidiEventCollection.cs", "_midi_event_collection_8cs.html", "_midi_event_collection_8cs" ],
    [ "MidiEventComparer.cs", "_midi_event_comparer_8cs.html", "_midi_event_comparer_8cs" ],
    [ "MidiFile.cs", "_midi_file_8cs.html", "_midi_file_8cs" ],
    [ "MidiIn.cs", "_midi_in_8cs.html", "_midi_in_8cs" ],
    [ "MidiInCapabilities.cs", "_midi_in_capabilities_8cs.html", "_midi_in_capabilities_8cs" ],
    [ "MidiInMessageEventArgs.cs", "_midi_in_message_event_args_8cs.html", "_midi_in_message_event_args_8cs" ],
    [ "MidiInSysexMessageEventArgs.cs", "_midi_in_sysex_message_event_args_8cs.html", "_midi_in_sysex_message_event_args_8cs" ],
    [ "MidiInterop.cs", "_midi_interop_8cs.html", "_midi_interop_8cs" ],
    [ "MidiMessage.cs", "_midi_message_8cs.html", "_midi_message_8cs" ],
    [ "MidiOut.cs", "_midi_out_8cs.html", "_midi_out_8cs" ],
    [ "MidiOutCapabilities.cs", "_midi_out_capabilities_8cs.html", "_midi_out_capabilities_8cs" ],
    [ "MidiOutTechnology.cs", "_midi_out_technology_8cs.html", "_midi_out_technology_8cs" ],
    [ "NoteEvent.cs", "_note_event_8cs.html", "_note_event_8cs" ],
    [ "NoteOnEvent.cs", "_note_on_event_8cs.html", "_note_on_event_8cs" ],
    [ "PatchChangeEvent.cs", "_patch_change_event_8cs.html", "_patch_change_event_8cs" ],
    [ "PitchWheelChangeEvent.cs", "_pitch_wheel_change_event_8cs.html", "_pitch_wheel_change_event_8cs" ],
    [ "RawMetaEvent.cs", "_raw_meta_event_8cs.html", "_raw_meta_event_8cs" ],
    [ "SequencerSpecificEvent.cs", "_sequencer_specific_event_8cs.html", "_sequencer_specific_event_8cs" ],
    [ "SmpteOffsetEvent.cs", "_smpte_offset_event_8cs.html", "_smpte_offset_event_8cs" ],
    [ "SysexEvent.cs", "_sysex_event_8cs.html", "_sysex_event_8cs" ],
    [ "TempoEvent.cs", "_tempo_event_8cs.html", "_tempo_event_8cs" ],
    [ "TextEvent.cs", "_text_event_8cs.html", "_text_event_8cs" ],
    [ "TimeSignatureEvent.cs", "_time_signature_event_8cs.html", "_time_signature_event_8cs" ],
    [ "TrackSequenceNumberEvent.cs", "_track_sequence_number_event_8cs.html", "_track_sequence_number_event_8cs" ]
];