var dir_3a512ed96ce9a29f0718aa33ad2b36b2 =
[
    [ "AdsrSampleProvider.cs", "_adsr_sample_provider_8cs.html", "_adsr_sample_provider_8cs" ],
    [ "ConcatenatingSampleProvider.cs", "_concatenating_sample_provider_8cs.html", "_concatenating_sample_provider_8cs" ],
    [ "FadeInOutSampleProvider.cs", "_fade_in_out_sample_provider_8cs.html", "_fade_in_out_sample_provider_8cs" ],
    [ "MeteringSampleProvider.cs", "_metering_sample_provider_8cs.html", "_metering_sample_provider_8cs" ],
    [ "MixingSampleProvider.cs", "_mixing_sample_provider_8cs.html", "_mixing_sample_provider_8cs" ],
    [ "MonoToStereoSampleProvider.cs", "_mono_to_stereo_sample_provider_8cs.html", "_mono_to_stereo_sample_provider_8cs" ],
    [ "MultiplexingSampleProvider.cs", "_multiplexing_sample_provider_8cs.html", "_multiplexing_sample_provider_8cs" ],
    [ "NotifyingSampleProvider.cs", "_notifying_sample_provider_8cs.html", "_notifying_sample_provider_8cs" ],
    [ "OffsetSampleProvider.cs", "_offset_sample_provider_8cs.html", "_offset_sample_provider_8cs" ],
    [ "PanningSampleProvider.cs", "_panning_sample_provider_8cs.html", "_panning_sample_provider_8cs" ],
    [ "Pcm16BitToSampleProvider.cs", "_pcm16_bit_to_sample_provider_8cs.html", "_pcm16_bit_to_sample_provider_8cs" ],
    [ "Pcm24BitToSampleProvider.cs", "_pcm24_bit_to_sample_provider_8cs.html", "_pcm24_bit_to_sample_provider_8cs" ],
    [ "Pcm32BitToSampleProvider.cs", "_pcm32_bit_to_sample_provider_8cs.html", "_pcm32_bit_to_sample_provider_8cs" ],
    [ "Pcm8BitToSampleProvider.cs", "_pcm8_bit_to_sample_provider_8cs.html", "_pcm8_bit_to_sample_provider_8cs" ],
    [ "SampleChannel.cs", "_sample_channel_8cs.html", "_sample_channel_8cs" ],
    [ "SampleProviderConverterBase.cs", "_sample_provider_converter_base_8cs.html", "_sample_provider_converter_base_8cs" ],
    [ "SampleProviderConverters.cs", "_sample_provider_converters_8cs.html", "_sample_provider_converters_8cs" ],
    [ "SampleToWaveProvider.cs", "_sample_to_wave_provider_8cs.html", "_sample_to_wave_provider_8cs" ],
    [ "SampleToWaveProvider16.cs", "_sample_to_wave_provider16_8cs.html", "_sample_to_wave_provider16_8cs" ],
    [ "SampleToWaveProvider24.cs", "_sample_to_wave_provider24_8cs.html", "_sample_to_wave_provider24_8cs" ],
    [ "SignalGenerator.cs", "_signal_generator_8cs.html", "_signal_generator_8cs" ],
    [ "SMBPitchShiftingSampleProvider.cs", "_s_m_b_pitch_shifting_sample_provider_8cs.html", "_s_m_b_pitch_shifting_sample_provider_8cs" ],
    [ "StereoToMonoSampleProvider.cs", "_stereo_to_mono_sample_provider_8cs.html", "_stereo_to_mono_sample_provider_8cs" ],
    [ "VolumeSampleProvider.cs", "_volume_sample_provider_8cs.html", "_volume_sample_provider_8cs" ],
    [ "WaveToSampleProvider.cs", "_wave_to_sample_provider_8cs.html", "_wave_to_sample_provider_8cs" ],
    [ "WaveToSampleProvider64.cs", "_wave_to_sample_provider64_8cs.html", "_wave_to_sample_provider64_8cs" ],
    [ "WdlResamplingSampleProvider.cs", "_wdl_resampling_sample_provider_8cs.html", "_wdl_resampling_sample_provider_8cs" ]
];