var hierarchy =
[
    [ "xeno_rat_server._listener", "classxeno__rat__server_1_1__listener.html", null ],
    [ "Hidden_handler._ProcessHelper", "class_hidden__handler_1_1___process_helper.html", null ],
    [ "NAudio.Wave.Compression.AcmDriverDetails", "struct_n_audio_1_1_wave_1_1_compression_1_1_acm_driver_details.html", null ],
    [ "NAudio.Wave.Compression.AcmFormat", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_format.html", null ],
    [ "NAudio.Wave.Compression.AcmFormatChoose", "struct_n_audio_1_1_wave_1_1_compression_1_1_acm_format_choose.html", null ],
    [ "NAudio.Wave.Compression.AcmFormatDetails", "struct_n_audio_1_1_wave_1_1_compression_1_1_acm_format_details.html", null ],
    [ "NAudio.Wave.Compression.AcmFormatTag", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_format_tag.html", null ],
    [ "NAudio.Wave.Compression.AcmFormatTagDetails", "struct_n_audio_1_1_wave_1_1_compression_1_1_acm_format_tag_details.html", null ],
    [ "NAudio.Wave.Compression.AcmInterop", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_interop.html", null ],
    [ "NAudio.Wave.Compression.AcmStreamHeaderStruct", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_stream_header_struct.html", null ],
    [ "xeno_rat_server.Forms.Socks5Const.AddressType", "classxeno__rat__server_1_1_forms_1_1_socks5_const_1_1_address_type.html", null ],
    [ "NAudio.Wave.AiffFileReader.AiffChunk", "struct_n_audio_1_1_wave_1_1_aiff_file_reader_1_1_aiff_chunk.html", null ],
    [ "NAudio.Codecs.ALawDecoder", "class_n_audio_1_1_codecs_1_1_a_law_decoder.html", null ],
    [ "NAudio.Codecs.ALawEncoder", "class_n_audio_1_1_codecs_1_1_a_law_encoder.html", null ],
    [ "NAudio.Wave.Asio.Asio64Bit", "struct_n_audio_1_1_wave_1_1_asio_1_1_asio64_bit.html", null ],
    [ "NAudio.Wave.Asio.AsioCallbacks", "struct_n_audio_1_1_wave_1_1_asio_1_1_asio_callbacks.html", null ],
    [ "NAudio.Wave.Asio.AsioChannelInfo", "struct_n_audio_1_1_wave_1_1_asio_1_1_asio_channel_info.html", null ],
    [ "NAudio.Wave.Asio.AsioDriver", "class_n_audio_1_1_wave_1_1_asio_1_1_asio_driver.html", null ],
    [ "NAudio.Wave.Asio.AsioDriverCapability", "class_n_audio_1_1_wave_1_1_asio_1_1_asio_driver_capability.html", null ],
    [ "NAudio.Wave.Asio.AsioDriverExt", "class_n_audio_1_1_wave_1_1_asio_1_1_asio_driver_ext.html", null ],
    [ "NAudio.Wave.Asio.AsioDriver.AsioDriverVTable", "class_n_audio_1_1_wave_1_1_asio_1_1_asio_driver_1_1_asio_driver_v_table.html", null ],
    [ "NAudio.Dsp.AttRelEnvelope", "class_n_audio_1_1_dsp_1_1_att_rel_envelope.html", [
      [ "NAudio.Dsp.SimpleCompressor", "class_n_audio_1_1_dsp_1_1_simple_compressor.html", null ],
      [ "NAudio.Dsp.SimpleGate", "class_n_audio_1_1_dsp_1_1_simple_gate.html", null ]
    ] ],
    [ "Attribute", "class_attribute.html", [
      [ "NAudio.Utils.FieldDescriptionAttribute", "class_n_audio_1_1_utils_1_1_field_description_attribute.html", null ]
    ] ],
    [ "NAudio.CoreAudioApi.AudioClientActivationParams", "struct_n_audio_1_1_core_audio_api_1_1_audio_client_activation_params.html", null ],
    [ "NAudio.CoreAudioApi.AudioClientProcessLoopbackParams", "struct_n_audio_1_1_core_audio_api_1_1_audio_client_process_loopback_params.html", null ],
    [ "NAudio.CoreAudioApi.AudioClientProperties", "struct_n_audio_1_1_core_audio_api_1_1_audio_client_properties.html", null ],
    [ "NAudio.CoreAudioApi.AudioEndpointVolumeChannel", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume_channel.html", null ],
    [ "NAudio.CoreAudioApi.AudioEndpointVolumeChannels", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume_channels.html", null ],
    [ "NAudio.CoreAudioApi.AudioEndpointVolumeStepInformation", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume_step_information.html", null ],
    [ "NAudio.CoreAudioApi.AudioEndpointVolumeVolumeRange", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume_volume_range.html", null ],
    [ "NAudio.Dmo.AudioMediaSubtypes", "class_n_audio_1_1_dmo_1_1_audio_media_subtypes.html", null ],
    [ "NAudio.CoreAudioApi.AudioMeterInformation", "class_n_audio_1_1_core_audio_api_1_1_audio_meter_information.html", null ],
    [ "NAudio.CoreAudioApi.AudioMeterInformationChannels", "class_n_audio_1_1_core_audio_api_1_1_audio_meter_information_channels.html", null ],
    [ "xeno_rat_server.Forms.AudioPlayer", "classxeno__rat__server_1_1_forms_1_1_audio_player.html", null ],
    [ "NAudio.CoreAudioApi.AudioSessionManager", "class_n_audio_1_1_core_audio_api_1_1_audio_session_manager.html", null ],
    [ "NAudio.MediaFoundation.AudioSubtypes", "class_n_audio_1_1_media_foundation_1_1_audio_subtypes.html", null ],
    [ "NAudio.CoreAudioApi.AudioVolumeNotificationData", "class_n_audio_1_1_core_audio_api_1_1_audio_volume_notification_data.html", null ],
    [ "xeno_rat_server.Forms.Socks5Const.AuthMethod", "classxeno__rat__server_1_1_forms_1_1_socks5_const_1_1_auth_method.html", null ],
    [ "NAudio.Codecs.Band", "class_n_audio_1_1_codecs_1_1_band.html", null ],
    [ "NAudio.Wave.BextChunkInfo", "class_n_audio_1_1_wave_1_1_bext_chunk_info.html", null ],
    [ "NAudio.Dsp.BiQuadFilter", "class_n_audio_1_1_dsp_1_1_bi_quad_filter.html", null ],
    [ "xeno_rat_server.IconInjector.BITMAPINFOHEADER", "structxeno__rat__server_1_1_icon_injector_1_1_b_i_t_m_a_p_i_n_f_o_h_e_a_d_e_r.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.Blob", "struct_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_blob.html", null ],
    [ "NAudio.Mixer.MixerInterop.Bounds", "struct_n_audio_1_1_mixer_1_1_mixer_interop_1_1_bounds.html", null ],
    [ "NAudio.Utils.BufferHelpers", "class_n_audio_1_1_utils_1_1_buffer_helpers.html", null ],
    [ "NAudio.Utils.ByteArrayExtensions", "class_n_audio_1_1_utils_1_1_byte_array_extensions.html", null ],
    [ "Plugin.Chromium", "class_plugin_1_1_chromium.html", null ],
    [ "NAudio.Utils.ChunkIdentifier", "class_n_audio_1_1_utils_1_1_chunk_identifier.html", null ],
    [ "NAudio.Utils.CircularBuffer", "class_n_audio_1_1_utils_1_1_circular_buffer.html", null ],
    [ "CollectionBase", "class_collection_base.html", [
      [ "AForge.Video.DirectShow.FilterInfoCollection", "class_a_forge_1_1_video_1_1_direct_show_1_1_filter_info_collection.html", null ]
    ] ],
    [ "xeno_rat_server.Forms.Socks5Const.Command", "classxeno__rat__server_1_1_forms_1_1_socks5_const_1_1_command.html", null ],
    [ "NAudio.Dsp.Complex", "struct_n_audio_1_1_dsp_1_1_complex.html", null ],
    [ "xeno_rat_client.Compression", "classxeno__rat__client_1_1_compression.html", null ],
    [ "xeno_rat_server.Compression", "classxeno__rat__server_1_1_compression.html", null ],
    [ "NAudio.CoreAudioApi.Connector", "class_n_audio_1_1_core_audio_api_1_1_connector.html", null ],
    [ "Plugin.Chromium.Cookie", "class_plugin_1_1_chromium_1_1_cookie.html", null ],
    [ "xeno_rat_server.Forms.Cookie", "classxeno__rat__server_1_1_forms_1_1_cookie.html", null ],
    [ "Plugin.Chromium.CreditCard", "class_plugin_1_1_chromium_1_1_credit_card.html", null ],
    [ "xeno_rat_server.Forms.CreditCard", "classxeno__rat__server_1_1_forms_1_1_credit_card.html", null ],
    [ "Plugin.SystemUtility.CShellWindows", "class_plugin_1_1_system_utility_1_1_c_shell_windows.html", null ],
    [ "NAudio.Wave.Cue", "class_n_audio_1_1_wave_1_1_cue.html", null ],
    [ "NAudio.Wave.CueList", "class_n_audio_1_1_wave_1_1_cue_list.html", null ],
    [ "Plugin.ScreenshotTaker.CURSORINFO", "struct_plugin_1_1_screenshot_taker_1_1_c_u_r_s_o_r_i_n_f_o.html", null ],
    [ "NAudio.Utils.Decibels", "class_n_audio_1_1_utils_1_1_decibels.html", null ],
    [ "NAudio.CoreAudioApi.DeviceTopology", "class_n_audio_1_1_core_audio_api_1_1_device_topology.html", null ],
    [ "NAudio.Wave.DirectSoundDeviceInfo", "class_n_audio_1_1_wave_1_1_direct_sound_device_info.html", null ],
    [ "xeno_rat_client.DllHandler", "classxeno__rat__client_1_1_dll_handler.html", null ],
    [ "NAudio.Dmo.DmoDescriptor", "class_n_audio_1_1_dmo_1_1_dmo_descriptor.html", null ],
    [ "NAudio.Dmo.DmoEnumerator", "class_n_audio_1_1_dmo_1_1_dmo_enumerator.html", null ],
    [ "NAudio.Dmo.DmoGuids", "class_n_audio_1_1_dmo_1_1_dmo_guids.html", null ],
    [ "NAudio.Dmo.DmoInterop", "class_n_audio_1_1_dmo_1_1_dmo_interop.html", null ],
    [ "NAudio.Dmo.DmoMediaType", "struct_n_audio_1_1_dmo_1_1_dmo_media_type.html", null ],
    [ "NAudio.Dmo.DmoMediaTypeGuids", "class_n_audio_1_1_dmo_1_1_dmo_media_type_guids.html", null ],
    [ "NAudio.Dmo.DmoPartialMediaType", "struct_n_audio_1_1_dmo_1_1_dmo_partial_media_type.html", null ],
    [ "Plugin.Chromium.Download", "class_plugin_1_1_chromium_1_1_download.html", null ],
    [ "xeno_rat_server.Forms.Download", "classxeno__rat__server_1_1_forms_1_1_download.html", null ],
    [ "Encoding", "class_encoding.html", [
      [ "NAudio.Utils.ByteEncoding", "class_n_audio_1_1_utils_1_1_byte_encoding.html", null ]
    ] ],
    [ "xeno_rat_client.Encryption", "classxeno__rat__client_1_1_encryption.html", null ],
    [ "xeno_rat_server.Encryption", "classxeno__rat__server_1_1_encryption.html", null ],
    [ "NAudio.Dsp.EnvelopeDetector", "class_n_audio_1_1_dsp_1_1_envelope_detector.html", null ],
    [ "NAudio.Dsp.EnvelopeGenerator", "class_n_audio_1_1_dsp_1_1_envelope_generator.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.ErrorCodes", "class_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_error_codes.html", null ],
    [ "EventArgs", "class_event_args.html", [
      [ "AForge.Video.NewFrameEventArgs", "class_a_forge_1_1_video_1_1_new_frame_event_args.html", null ],
      [ "AForge.Video.VideoSourceErrorEventArgs", "class_a_forge_1_1_video_1_1_video_source_error_event_args.html", null ],
      [ "NAudio.Midi.MidiInMessageEventArgs", "class_n_audio_1_1_midi_1_1_midi_in_message_event_args.html", null ],
      [ "NAudio.Midi.MidiInSysexMessageEventArgs", "class_n_audio_1_1_midi_1_1_midi_in_sysex_message_event_args.html", null ],
      [ "NAudio.Wave.AsioAudioAvailableEventArgs", "class_n_audio_1_1_wave_1_1_asio_audio_available_event_args.html", null ],
      [ "NAudio.Wave.SampleEventArgs", "class_n_audio_1_1_wave_1_1_sample_event_args.html", null ],
      [ "NAudio.Wave.SampleProviders.SampleProviderEventArgs", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_event_args.html", null ],
      [ "NAudio.Wave.SampleProviders.StreamVolumeEventArgs", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stream_volume_event_args.html", null ],
      [ "NAudio.Wave.StoppedEventArgs", "class_n_audio_1_1_wave_1_1_stopped_event_args.html", null ],
      [ "NAudio.Wave.WaveInEventArgs", "class_n_audio_1_1_wave_1_1_wave_in_event_args.html", null ]
    ] ],
    [ "Exception", "class_exception.html", [
      [ "NAudio.MmException", "class_n_audio_1_1_mm_exception.html", null ]
    ] ],
    [ "NAudio.Dsp.FastFourierTransform", "class_n_audio_1_1_dsp_1_1_fast_fourier_transform.html", null ],
    [ "NAudio.Utils.FieldDescriptionHelper", "class_n_audio_1_1_utils_1_1_field_description_helper.html", null ],
    [ "xeno_rat_server.Forms.FileData", "classxeno__rat__server_1_1_forms_1_1_file_data.html", null ],
    [ "xeno_rat_server.Forms.FileView", "classxeno__rat__server_1_1_forms_1_1_file_view.html", null ],
    [ "AForge.Video.DirectShow.FilterCategory", "class_a_forge_1_1_video_1_1_direct_show_1_1_filter_category.html", null ],
    [ "Form", "class_form.html", [
      [ "Chat.ChatForm", "class_chat_1_1_chat_form.html", null ],
      [ "NAudio.Wave.WaveWindow", "class_n_audio_1_1_wave_1_1_wave_window.html", null ],
      [ "xeno_rat_server.Forms.Chat", "classxeno__rat__server_1_1_forms_1_1_chat.html", null ],
      [ "xeno_rat_server.Forms.DebugInfo", "classxeno__rat__server_1_1_forms_1_1_debug_info.html", null ],
      [ "xeno_rat_server.Forms.File_manager", "classxeno__rat__server_1_1_forms_1_1_file__manager.html", null ],
      [ "xeno_rat_server.Forms.FunMenu", "classxeno__rat__server_1_1_forms_1_1_fun_menu.html", null ],
      [ "xeno_rat_server.Forms.Hvnc", "classxeno__rat__server_1_1_forms_1_1_hvnc.html", null ],
      [ "xeno_rat_server.Forms.InfoGrab", "classxeno__rat__server_1_1_forms_1_1_info_grab.html", null ],
      [ "xeno_rat_server.Forms.KeyLogger", "classxeno__rat__server_1_1_forms_1_1_key_logger.html", null ],
      [ "xeno_rat_server.Forms.Live_Microphone", "classxeno__rat__server_1_1_forms_1_1_live___microphone.html", null ],
      [ "xeno_rat_server.Forms.OfflineKeylogger", "classxeno__rat__server_1_1_forms_1_1_offline_keylogger.html", null ],
      [ "xeno_rat_server.Forms.ProcessManager", "classxeno__rat__server_1_1_forms_1_1_process_manager.html", null ],
      [ "xeno_rat_server.Forms.Registry_Manager", "classxeno__rat__server_1_1_forms_1_1_registry___manager.html", null ],
      [ "xeno_rat_server.Forms.Reverse_Proxy", "classxeno__rat__server_1_1_forms_1_1_reverse___proxy.html", null ],
      [ "xeno_rat_server.Forms.ScreenControl", "classxeno__rat__server_1_1_forms_1_1_screen_control.html", null ],
      [ "xeno_rat_server.Forms.Shell", "classxeno__rat__server_1_1_forms_1_1_shell.html", null ],
      [ "xeno_rat_server.Forms.WebCam", "classxeno__rat__server_1_1_forms_1_1_web_cam.html", null ],
      [ "xeno_rat_server.MainForm", "classxeno__rat__server_1_1_main_form.html", null ]
    ] ],
    [ "NAudio.Codecs.G722Codec", "class_n_audio_1_1_codecs_1_1_g722_codec.html", null ],
    [ "NAudio.Codecs.G722CodecState", "class_n_audio_1_1_codecs_1_1_g722_codec_state.html", null ],
    [ "NAudio.SoundFont.Generator", "class_n_audio_1_1_sound_font_1_1_generator.html", null ],
    [ "AForge.Video.DirectShow.VideoCaptureDevice.Grabber", "class_a_forge_1_1_video_1_1_direct_show_1_1_video_capture_device_1_1_grabber.html", null ],
    [ "xeno_rat_server.IconInjector.GRPICONDIRENTRY", "structxeno__rat__server_1_1_icon_injector_1_1_g_r_p_i_c_o_n_d_i_r_e_n_t_r_y.html", null ],
    [ "xeno_rat_client.Handler", "classxeno__rat__client_1_1_handler.html", null ],
    [ "xeno_rat_client.header", "classxeno__rat__client_1_1header.html", null ],
    [ "xeno_rat_server.header", "classxeno__rat__server_1_1header.html", null ],
    [ "NAudio.Utils.HResult", "class_n_audio_1_1_utils_1_1_h_result.html", null ],
    [ "NAudio.Wasapi.CoreAudioApi.Interfaces.IActivateAudioInterfaceAsyncOperation", "interface_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_interfaces_1_1_i_activate_audio_interface_async_operation.html", null ],
    [ "NAudio.Wasapi.CoreAudioApi.Interfaces.IActivateAudioInterfaceCompletionHandler", "interface_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_interfaces_1_1_i_activate_audio_interface_completion_handler.html", null ],
    [ "NAudio.Wasapi.CoreAudioApi.Interfaces.IAgileObject", "interface_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_interfaces_1_1_i_agile_object.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.IAudioCaptureClient", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_capture_client.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.IAudioClient", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_client.html", [
      [ "NAudio.CoreAudioApi.Interfaces.IAudioClient2", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_client2.html", null ]
    ] ],
    [ "Plugin.IAudioEndpointVolume", "interface_plugin_1_1_i_audio_endpoint_volume.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.IAudioRenderClient", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_render_client.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.IAudioSessionControl", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_control.html", [
      [ "NAudio.CoreAudioApi.Interfaces.IAudioSessionControl2", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_control2.html", null ]
    ] ],
    [ "NAudio.CoreAudioApi.Interfaces.IAudioSessionEvents", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_events.html", [
      [ "NAudio.CoreAudioApi.AudioSessionEventsCallback", "class_n_audio_1_1_core_audio_api_1_1_audio_session_events_callback.html", null ]
    ] ],
    [ "NAudio.CoreAudioApi.Interfaces.IAudioSessionEventsHandler", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_events_handler.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.IAudioSessionNotification", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_notification.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.IAudioStreamVolume", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_stream_volume.html", null ],
    [ "ICloneable", "class_i_cloneable.html", [
      [ "NAudio.Midi.MidiEvent", "class_n_audio_1_1_midi_1_1_midi_event.html", [
        [ "NAudio.Midi.ChannelAfterTouchEvent", "class_n_audio_1_1_midi_1_1_channel_after_touch_event.html", null ],
        [ "NAudio.Midi.ControlChangeEvent", "class_n_audio_1_1_midi_1_1_control_change_event.html", null ],
        [ "NAudio.Midi.MetaEvent", "class_n_audio_1_1_midi_1_1_meta_event.html", [
          [ "NAudio.Midi.KeySignatureEvent", "class_n_audio_1_1_midi_1_1_key_signature_event.html", null ],
          [ "NAudio.Midi.RawMetaEvent", "class_n_audio_1_1_midi_1_1_raw_meta_event.html", null ],
          [ "NAudio.Midi.SequencerSpecificEvent", "class_n_audio_1_1_midi_1_1_sequencer_specific_event.html", null ],
          [ "NAudio.Midi.SmpteOffsetEvent", "class_n_audio_1_1_midi_1_1_smpte_offset_event.html", null ],
          [ "NAudio.Midi.TempoEvent", "class_n_audio_1_1_midi_1_1_tempo_event.html", null ],
          [ "NAudio.Midi.TextEvent", "class_n_audio_1_1_midi_1_1_text_event.html", null ],
          [ "NAudio.Midi.TimeSignatureEvent", "class_n_audio_1_1_midi_1_1_time_signature_event.html", null ],
          [ "NAudio.Midi.TrackSequenceNumberEvent", "class_n_audio_1_1_midi_1_1_track_sequence_number_event.html", null ]
        ] ],
        [ "NAudio.Midi.NoteEvent", "class_n_audio_1_1_midi_1_1_note_event.html", [
          [ "NAudio.Midi.NoteOnEvent", "class_n_audio_1_1_midi_1_1_note_on_event.html", null ]
        ] ],
        [ "NAudio.Midi.PatchChangeEvent", "class_n_audio_1_1_midi_1_1_patch_change_event.html", null ],
        [ "NAudio.Midi.PitchWheelChangeEvent", "class_n_audio_1_1_midi_1_1_pitch_wheel_change_event.html", null ],
        [ "NAudio.Midi.SysexEvent", "class_n_audio_1_1_midi_1_1_sysex_event.html", null ]
      ] ]
    ] ],
    [ "IComparable", "class_i_comparable.html", [
      [ "AForge.Video.DirectShow.FilterInfo", "class_a_forge_1_1_video_1_1_direct_show_1_1_filter_info.html", null ]
    ] ],
    [ "IComparer", "class_i_comparer.html", [
      [ "NAudio.Midi.MidiEventComparer", "class_n_audio_1_1_midi_1_1_midi_event_comparer.html", null ]
    ] ],
    [ "xeno_rat_server.IconInjector.ICONDIR", "structxeno__rat__server_1_1_icon_injector_1_1_i_c_o_n_d_i_r.html", null ],
    [ "xeno_rat_server.IconInjector.ICONDIRENTRY", "structxeno__rat__server_1_1_icon_injector_1_1_i_c_o_n_d_i_r_e_n_t_r_y.html", null ],
    [ "xeno_rat_server.IconInjector.IconFile", "classxeno__rat__server_1_1_icon_injector_1_1_icon_file.html", null ],
    [ "xeno_rat_server.IconInjector", "classxeno__rat__server_1_1_icon_injector.html", null ],
    [ "ICustomMarshaler", "class_i_custom_marshaler.html", [
      [ "NAudio.Wave.WaveFormatCustomMarshaler", "class_n_audio_1_1_wave_1_1_wave_format_custom_marshaler.html", null ]
    ] ],
    [ "NAudio.Wave.Id3v2Tag", "class_n_audio_1_1_wave_1_1_id3v2_tag.html", null ],
    [ "NAudio.Dmo.Effect.IDirectSoundFXCompressor", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_compressor.html", null ],
    [ "NAudio.Dmo.Effect.IDirectSoundFXDistortion", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_distortion.html", null ],
    [ "NAudio.Dmo.Effect.IDirectSoundFXEcho", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_echo.html", null ],
    [ "NAudio.Dmo.Effect.IDirectSoundFXFlanger", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_flanger.html", null ],
    [ "NAudio.Dmo.Effect.IDirectSoundFXGargle", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_gargle.html", null ],
    [ "NAudio.Dmo.Effect.IDirectSoundFXI3DL2Reverb", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_i3_d_l2_reverb.html", null ],
    [ "NAudio.Dmo.Effect.IDirectSoundFxParamEq", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_fx_param_eq.html", null ],
    [ "NAudio.Dmo.Effect.IDirectSoundFXWavesReverb", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_waves_reverb.html", null ],
    [ "Plugin.SystemUtility.IDispatch", "interface_plugin_1_1_system_utility_1_1_i_dispatch.html", null ],
    [ "IDisposable", "class_i_disposable.html", [
      [ "NAudio.CoreAudioApi.AudioCaptureClient", "class_n_audio_1_1_core_audio_api_1_1_audio_capture_client.html", null ],
      [ "NAudio.CoreAudioApi.AudioClient", "class_n_audio_1_1_core_audio_api_1_1_audio_client.html", null ],
      [ "NAudio.CoreAudioApi.AudioClockClient", "class_n_audio_1_1_core_audio_api_1_1_audio_clock_client.html", null ],
      [ "NAudio.CoreAudioApi.AudioEndpointVolume", "class_n_audio_1_1_core_audio_api_1_1_audio_endpoint_volume.html", null ],
      [ "NAudio.CoreAudioApi.AudioRenderClient", "class_n_audio_1_1_core_audio_api_1_1_audio_render_client.html", null ],
      [ "NAudio.CoreAudioApi.AudioSessionControl", "class_n_audio_1_1_core_audio_api_1_1_audio_session_control.html", null ],
      [ "NAudio.CoreAudioApi.AudioStreamVolume", "class_n_audio_1_1_core_audio_api_1_1_audio_stream_volume.html", null ],
      [ "NAudio.CoreAudioApi.MMDevice", "class_n_audio_1_1_core_audio_api_1_1_m_m_device.html", null ],
      [ "NAudio.CoreAudioApi.MMDeviceEnumerator", "class_n_audio_1_1_core_audio_api_1_1_m_m_device_enumerator.html", null ],
      [ "NAudio.CoreAudioApi.SimpleAudioVolume", "class_n_audio_1_1_core_audio_api_1_1_simple_audio_volume.html", null ],
      [ "NAudio.Dmo.DmoOutputDataBuffer", "struct_n_audio_1_1_dmo_1_1_dmo_output_data_buffer.html", null ],
      [ "NAudio.Dmo.DmoResampler", "class_n_audio_1_1_dmo_1_1_dmo_resampler.html", null ],
      [ "NAudio.Dmo.Effect.IDmoEffector< out TParameters >", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html", null ],
      [ "NAudio.Dmo.MediaBuffer", "class_n_audio_1_1_dmo_1_1_media_buffer.html", null ],
      [ "NAudio.Dmo.MediaObject", "class_n_audio_1_1_dmo_1_1_media_object.html", null ],
      [ "NAudio.Dmo.MediaObjectInPlace", "class_n_audio_1_1_dmo_1_1_media_object_in_place.html", null ],
      [ "NAudio.Dmo.WindowsMediaMp3Decoder", "class_n_audio_1_1_dmo_1_1_windows_media_mp3_decoder.html", null ],
      [ "NAudio.MediaFoundation.MediaFoundationTransform", "class_n_audio_1_1_media_foundation_1_1_media_foundation_transform.html", [
        [ "NAudio.Wave.MediaFoundationResampler", "class_n_audio_1_1_wave_1_1_media_foundation_resampler.html", null ]
      ] ],
      [ "NAudio.Midi.MidiIn", "class_n_audio_1_1_midi_1_1_midi_in.html", null ],
      [ "NAudio.Midi.MidiOut", "class_n_audio_1_1_midi_1_1_midi_out.html", null ],
      [ "NAudio.Wave.BwfWriter", "class_n_audio_1_1_wave_1_1_bwf_writer.html", null ],
      [ "NAudio.Wave.Compression.AcmDriver", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_driver.html", null ],
      [ "NAudio.Wave.Compression.AcmStream", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_stream.html", null ],
      [ "NAudio.Wave.Compression.AcmStreamHeader", "class_n_audio_1_1_wave_1_1_compression_1_1_acm_stream_header.html", null ],
      [ "NAudio.Wave.DmoEffectWaveProvider< TDmoEffector, TEffectorParam >", "class_n_audio_1_1_wave_1_1_dmo_effect_wave_provider.html", null ],
      [ "NAudio.Wave.IMp3FrameDecompressor", "interface_n_audio_1_1_wave_1_1_i_mp3_frame_decompressor.html", [
        [ "NAudio.FileFormats.Mp3.DmoMp3FrameDecompressor", "class_n_audio_1_1_file_formats_1_1_mp3_1_1_dmo_mp3_frame_decompressor.html", null ],
        [ "NAudio.Wave.AcmMp3FrameDecompressor", "class_n_audio_1_1_wave_1_1_acm_mp3_frame_decompressor.html", null ]
      ] ],
      [ "NAudio.Wave.IWaveIn", "interface_n_audio_1_1_wave_1_1_i_wave_in.html", [
        [ "NAudio.CoreAudioApi.WasapiCapture", "class_n_audio_1_1_core_audio_api_1_1_wasapi_capture.html", [
          [ "NAudio.Wave.WasapiLoopbackCapture", "class_n_audio_1_1_wave_1_1_wasapi_loopback_capture.html", null ]
        ] ],
        [ "NAudio.Wave.WaveIn", "class_n_audio_1_1_wave_1_1_wave_in.html", null ],
        [ "NAudio.Wave.WaveInEvent", "class_n_audio_1_1_wave_1_1_wave_in_event.html", null ]
      ] ],
      [ "NAudio.Wave.IWavePlayer", "interface_n_audio_1_1_wave_1_1_i_wave_player.html", [
        [ "NAudio.Wave.AsioOut", "class_n_audio_1_1_wave_1_1_asio_out.html", null ],
        [ "NAudio.Wave.DirectSoundOut", "class_n_audio_1_1_wave_1_1_direct_sound_out.html", null ],
        [ "NAudio.Wave.WasapiOut", "class_n_audio_1_1_wave_1_1_wasapi_out.html", null ],
        [ "NAudio.Wave.WaveOut", "class_n_audio_1_1_wave_1_1_wave_out.html", null ],
        [ "NAudio.Wave.WaveOutEvent", "class_n_audio_1_1_wave_1_1_wave_out_event.html", null ]
      ] ],
      [ "NAudio.Wave.MediaFoundationEncoder", "class_n_audio_1_1_wave_1_1_media_foundation_encoder.html", null ],
      [ "NAudio.Wave.WaveFormatConversionProvider", "class_n_audio_1_1_wave_1_1_wave_format_conversion_provider.html", null ],
      [ "NAudio.Wave.WaveInBuffer", "class_n_audio_1_1_wave_1_1_wave_in_buffer.html", null ],
      [ "NAudio.Wave.WaveOutBuffer", "class_n_audio_1_1_wave_1_1_wave_out_buffer.html", null ],
      [ "NAudio.Wave.WaveRecorder", "class_n_audio_1_1_wave_1_1_wave_recorder.html", null ]
    ] ],
    [ "NAudio.Dmo.Effect.IDmoEffector< DmoChorus.Params >", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html", [
      [ "NAudio.Dmo.Effect.DmoChorus", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_chorus.html", null ]
    ] ],
    [ "NAudio.Dmo.Effect.IDmoEffector< DmoCompressor.Params >", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html", [
      [ "NAudio.Dmo.Effect.DmoCompressor", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_compressor.html", null ]
    ] ],
    [ "NAudio.Dmo.Effect.IDmoEffector< DmoDistortion.Params >", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html", [
      [ "NAudio.Dmo.Effect.DmoDistortion", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_distortion.html", null ]
    ] ],
    [ "NAudio.Dmo.Effect.IDmoEffector< DmoEcho.Params >", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html", [
      [ "NAudio.Dmo.Effect.DmoEcho", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_echo.html", null ]
    ] ],
    [ "NAudio.Dmo.Effect.IDmoEffector< DmoFlanger.Params >", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html", [
      [ "NAudio.Dmo.Effect.DmoFlanger", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_flanger.html", null ]
    ] ],
    [ "NAudio.Dmo.Effect.IDmoEffector< DmoGargle.Params >", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html", [
      [ "NAudio.Dmo.Effect.DmoGargle", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_gargle.html", null ]
    ] ],
    [ "NAudio.Dmo.Effect.IDmoEffector< DmoI3DL2Reverb.Params >", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html", [
      [ "NAudio.Dmo.Effect.DmoI3DL2Reverb", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_i3_d_l2_reverb.html", null ]
    ] ],
    [ "NAudio.Dmo.Effect.IDmoEffector< DmoParamEq.Params >", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html", [
      [ "NAudio.Dmo.Effect.DmoParamEq", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_param_eq.html", null ]
    ] ],
    [ "NAudio.Dmo.Effect.IDmoEffector< DmoWavesReverb.Params >", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html", [
      [ "NAudio.Dmo.Effect.DmoWavesReverb", "class_n_audio_1_1_dmo_1_1_effect_1_1_dmo_waves_reverb.html", null ]
    ] ],
    [ "NAudio.Dmo.Effect.IDmoEffector< TEffectorParam >", "interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html", null ],
    [ "NAudio.Utils.IEEE", "class_n_audio_1_1_utils_1_1_i_e_e_e.html", null ],
    [ "NAudio.Dmo.IEnumDmo", "interface_n_audio_1_1_dmo_1_1_i_enum_dmo.html", null ],
    [ "IEnumerable", "class_i_enumerable.html", [
      [ "NAudio.CoreAudioApi.MMDeviceCollection", "class_n_audio_1_1_core_audio_api_1_1_m_m_device_collection.html", null ],
      [ "NAudio.Midi.MidiEventCollection", "class_n_audio_1_1_midi_1_1_midi_event_collection.html", null ]
    ] ],
    [ "Hidden_handler.Imaging_handler", "class_hidden__handler_1_1_imaging__handler.html", null ],
    [ "NAudio.Dmo.IMediaBuffer", "interface_n_audio_1_1_dmo_1_1_i_media_buffer.html", [
      [ "NAudio.Dmo.MediaBuffer", "class_n_audio_1_1_dmo_1_1_media_buffer.html", null ]
    ] ],
    [ "NAudio.Dmo.IMediaObject", "interface_n_audio_1_1_dmo_1_1_i_media_object.html", null ],
    [ "NAudio.Dmo.IMediaParamInfo", "interface_n_audio_1_1_dmo_1_1_i_media_param_info.html", null ],
    [ "NAudio.MediaFoundation.IMFAttributes", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_attributes.html", [
      [ "NAudio.MediaFoundation.IMFActivate", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_activate.html", null ],
      [ "NAudio.MediaFoundation.IMFMediaEvent", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_media_event.html", null ],
      [ "NAudio.MediaFoundation.IMFMediaType", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_media_type.html", null ],
      [ "NAudio.MediaFoundation.IMFSample", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_sample.html", null ]
    ] ],
    [ "NAudio.MediaFoundation.IMFByteStream", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_byte_stream.html", null ],
    [ "NAudio.MediaFoundation.IMFCollection", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_collection.html", null ],
    [ "NAudio.MediaFoundation.IMFMediaBuffer", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_media_buffer.html", null ],
    [ "NAudio.MediaFoundation.IMFReadWriteClassFactory", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_read_write_class_factory.html", null ],
    [ "NAudio.MediaFoundation.IMFSinkWriter", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_sink_writer.html", null ],
    [ "NAudio.MediaFoundation.IMFSourceReader", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_source_reader.html", null ],
    [ "NAudio.MediaFoundation.IMFTransform", "interface_n_audio_1_1_media_foundation_1_1_i_m_f_transform.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.IMMDevice", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_device.html", null ],
    [ "Plugin.IMMDevice", "interface_plugin_1_1_i_m_m_device.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.IMMDeviceCollection", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_device_collection.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.IMMDeviceEnumerator", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_device_enumerator.html", null ],
    [ "Plugin.IMMDeviceEnumerator", "interface_plugin_1_1_i_m_m_device_enumerator.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.IMMEndpoint", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_endpoint.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.IMMNotificationClient", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_notification_client.html", null ],
    [ "NAudio.Dsp.ImpulseResponseConvolution", "class_n_audio_1_1_dsp_1_1_impulse_response_convolution.html", null ],
    [ "NAudio.SoundFont.InfoChunk", "class_n_audio_1_1_sound_font_1_1_info_chunk.html", null ],
    [ "Hidden_handler.input_handler", "class_hidden__handler_1_1input__handler.html", null ],
    [ "Plugin.InputHandler", "class_plugin_1_1_input_handler.html", null ],
    [ "NAudio.SoundFont.Instrument", "class_n_audio_1_1_sound_font_1_1_instrument.html", null ],
    [ "NAudio.Wave.SampleProviders.IPanStrategy", "interface_n_audio_1_1_wave_1_1_sample_providers_1_1_i_pan_strategy.html", [
      [ "NAudio.Wave.SampleProviders.LinearPanStrategy", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_linear_pan_strategy.html", null ],
      [ "NAudio.Wave.SampleProviders.SinPanStrategy", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sin_pan_strategy.html", null ],
      [ "NAudio.Wave.SampleProviders.SquareRootPanStrategy", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_square_root_pan_strategy.html", null ],
      [ "NAudio.Wave.SampleProviders.StereoBalanceStrategy", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_balance_strategy.html", null ]
    ] ],
    [ "NAudio.CoreAudioApi.Interfaces.IPropertyStore", "interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_property_store.html", null ],
    [ "NAudio.Wave.SampleProviders.ISampleChunkConverter", "interface_n_audio_1_1_wave_1_1_sample_providers_1_1_i_sample_chunk_converter.html", [
      [ "NAudio.Wave.SampleProviders.Mono16SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono16_sample_chunk_converter.html", null ],
      [ "NAudio.Wave.SampleProviders.Mono24SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono24_sample_chunk_converter.html", null ],
      [ "NAudio.Wave.SampleProviders.Mono8SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono8_sample_chunk_converter.html", null ],
      [ "NAudio.Wave.SampleProviders.MonoFloatSampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono_float_sample_chunk_converter.html", null ],
      [ "NAudio.Wave.SampleProviders.Stereo16SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo16_sample_chunk_converter.html", null ],
      [ "NAudio.Wave.SampleProviders.Stereo24SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo24_sample_chunk_converter.html", null ],
      [ "NAudio.Wave.SampleProviders.Stereo8SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo8_sample_chunk_converter.html", null ],
      [ "NAudio.Wave.SampleProviders.StereoFloatSampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_float_sample_chunk_converter.html", null ]
    ] ],
    [ "NAudio.Wave.ISampleNotifier", "interface_n_audio_1_1_wave_1_1_i_sample_notifier.html", [
      [ "NAudio.Wave.SampleProviders.NotifyingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_notifying_sample_provider.html", null ],
      [ "NAudio.Wave.WaveChannel32", "class_n_audio_1_1_wave_1_1_wave_channel32.html", null ]
    ] ],
    [ "NAudio.Wave.ISampleProvider", "interface_n_audio_1_1_wave_1_1_i_sample_provider.html", [
      [ "NAudio.Wave.SampleProviders.AdsrSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_adsr_sample_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.ConcatenatingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_concatenating_sample_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.FadeInOutSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_fade_in_out_sample_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.MeteringSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_metering_sample_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.MixingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mixing_sample_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.MonoToStereoSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono_to_stereo_sample_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.MultiplexingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_multiplexing_sample_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.NotifyingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_notifying_sample_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.OffsetSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_offset_sample_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.PanningSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_panning_sample_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.SampleChannel", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_channel.html", null ],
      [ "NAudio.Wave.SampleProviders.SampleProviderConverterBase", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_converter_base.html", [
        [ "NAudio.Wave.SampleProviders.Pcm16BitToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm16_bit_to_sample_provider.html", null ],
        [ "NAudio.Wave.SampleProviders.Pcm24BitToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm24_bit_to_sample_provider.html", null ],
        [ "NAudio.Wave.SampleProviders.Pcm32BitToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm32_bit_to_sample_provider.html", null ],
        [ "NAudio.Wave.SampleProviders.Pcm8BitToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm8_bit_to_sample_provider.html", null ],
        [ "NAudio.Wave.SampleProviders.WaveToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wave_to_sample_provider.html", null ],
        [ "NAudio.Wave.SampleProviders.WaveToSampleProvider64", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wave_to_sample_provider64.html", null ]
      ] ],
      [ "NAudio.Wave.SampleProviders.SignalGenerator", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_signal_generator.html", null ],
      [ "NAudio.Wave.SampleProviders.SmbPitchShiftingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_smb_pitch_shifting_sample_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.StereoToMonoSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_to_mono_sample_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.VolumeSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_volume_sample_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.WdlResamplingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wdl_resampling_sample_provider.html", null ],
      [ "NAudio.Wave.SimpleCompressorEffect", "class_n_audio_1_1_wave_1_1_simple_compressor_effect.html", null ],
      [ "NAudio.Wave.WaveProvider32", "class_n_audio_1_1_wave_1_1_wave_provider32.html", null ]
    ] ],
    [ "Plugin.SystemUtility.IServiceProvider", "interface_plugin_1_1_system_utility_1_1_i_service_provider.html", null ],
    [ "Plugin.SystemUtility.IShellBrowser", "interface_plugin_1_1_system_utility_1_1_i_shell_browser.html", null ],
    [ "Plugin.SystemUtility.IShellDispatch2", "interface_plugin_1_1_system_utility_1_1_i_shell_dispatch2.html", null ],
    [ "Plugin.SystemUtility.IShellFolderViewDual", "interface_plugin_1_1_system_utility_1_1_i_shell_folder_view_dual.html", null ],
    [ "Plugin.SystemUtility.IShellView", "interface_plugin_1_1_system_utility_1_1_i_shell_view.html", null ],
    [ "Plugin.SystemUtility.IShellWindows", "interface_plugin_1_1_system_utility_1_1_i_shell_windows.html", null ],
    [ "IStream", "class_i_stream.html", [
      [ "NAudio.Wave.ComStream", "class_n_audio_1_1_wave_1_1_com_stream.html", null ]
    ] ],
    [ "AForge.Video.IVideoSource", "interface_a_forge_1_1_video_1_1_i_video_source.html", [
      [ "AForge.Video.DirectShow.VideoCaptureDevice", "class_a_forge_1_1_video_1_1_direct_show_1_1_video_capture_device.html", null ]
    ] ],
    [ "NAudio.Wave.IWaveBuffer", "interface_n_audio_1_1_wave_1_1_i_wave_buffer.html", [
      [ "NAudio.Wave.WaveBuffer", "class_n_audio_1_1_wave_1_1_wave_buffer.html", null ]
    ] ],
    [ "NAudio.Wave.IWavePosition", "interface_n_audio_1_1_wave_1_1_i_wave_position.html", [
      [ "NAudio.Wave.WasapiOut", "class_n_audio_1_1_wave_1_1_wasapi_out.html", null ],
      [ "NAudio.Wave.WaveOut", "class_n_audio_1_1_wave_1_1_wave_out.html", null ],
      [ "NAudio.Wave.WaveOutEvent", "class_n_audio_1_1_wave_1_1_wave_out_event.html", null ]
    ] ],
    [ "NAudio.Wave.IWaveProvider", "interface_n_audio_1_1_wave_1_1_i_wave_provider.html", [
      [ "NAudio.MediaFoundation.MediaFoundationTransform", "class_n_audio_1_1_media_foundation_1_1_media_foundation_transform.html", null ],
      [ "NAudio.Wave.BufferedWaveProvider", "class_n_audio_1_1_wave_1_1_buffered_wave_provider.html", null ],
      [ "NAudio.Wave.DmoEffectWaveProvider< TDmoEffector, TEffectorParam >", "class_n_audio_1_1_wave_1_1_dmo_effect_wave_provider.html", null ],
      [ "NAudio.Wave.MixingWaveProvider32", "class_n_audio_1_1_wave_1_1_mixing_wave_provider32.html", null ],
      [ "NAudio.Wave.MonoToStereoProvider16", "class_n_audio_1_1_wave_1_1_mono_to_stereo_provider16.html", null ],
      [ "NAudio.Wave.MultiplexingWaveProvider", "class_n_audio_1_1_wave_1_1_multiplexing_wave_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.SampleToWaveProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider.html", null ],
      [ "NAudio.Wave.SampleProviders.SampleToWaveProvider16", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider16.html", null ],
      [ "NAudio.Wave.SampleProviders.SampleToWaveProvider24", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider24.html", null ],
      [ "NAudio.Wave.SilenceProvider", "class_n_audio_1_1_wave_1_1_silence_provider.html", null ],
      [ "NAudio.Wave.StereoToMonoProvider16", "class_n_audio_1_1_wave_1_1_stereo_to_mono_provider16.html", null ],
      [ "NAudio.Wave.VolumeWaveProvider16", "class_n_audio_1_1_wave_1_1_volume_wave_provider16.html", null ],
      [ "NAudio.Wave.Wave16ToFloatProvider", "class_n_audio_1_1_wave_1_1_wave16_to_float_provider.html", null ],
      [ "NAudio.Wave.WaveFloatTo16Provider", "class_n_audio_1_1_wave_1_1_wave_float_to16_provider.html", null ],
      [ "NAudio.Wave.WaveFormatConversionProvider", "class_n_audio_1_1_wave_1_1_wave_format_conversion_provider.html", null ],
      [ "NAudio.Wave.WaveInProvider", "class_n_audio_1_1_wave_1_1_wave_in_provider.html", null ],
      [ "NAudio.Wave.WaveProvider16", "class_n_audio_1_1_wave_1_1_wave_provider16.html", null ],
      [ "NAudio.Wave.WaveProvider32", "class_n_audio_1_1_wave_1_1_wave_provider32.html", null ],
      [ "NAudio.Wave.WaveRecorder", "class_n_audio_1_1_wave_1_1_wave_recorder.html", null ],
      [ "NAudio.Wave.WaveStream", "class_n_audio_1_1_wave_1_1_wave_stream.html", [
        [ "NAudio.Wave.AiffFileReader", "class_n_audio_1_1_wave_1_1_aiff_file_reader.html", null ],
        [ "NAudio.Wave.BlockAlignReductionStream", "class_n_audio_1_1_wave_1_1_block_align_reduction_stream.html", null ],
        [ "NAudio.Wave.MediaFoundationReader", "class_n_audio_1_1_wave_1_1_media_foundation_reader.html", [
          [ "NAudio.Wave.StreamMediaFoundationReader", "class_n_audio_1_1_wave_1_1_stream_media_foundation_reader.html", null ]
        ] ],
        [ "NAudio.Wave.Mp3FileReaderBase", "class_n_audio_1_1_wave_1_1_mp3_file_reader_base.html", null ],
        [ "NAudio.Wave.RawSourceWaveStream", "class_n_audio_1_1_wave_1_1_raw_source_wave_stream.html", null ],
        [ "NAudio.Wave.ResamplerDmoStream", "class_n_audio_1_1_wave_1_1_resampler_dmo_stream.html", null ],
        [ "NAudio.Wave.Wave32To16Stream", "class_n_audio_1_1_wave_1_1_wave32_to16_stream.html", null ],
        [ "NAudio.Wave.WaveChannel32", "class_n_audio_1_1_wave_1_1_wave_channel32.html", null ],
        [ "NAudio.Wave.WaveFileReader", "class_n_audio_1_1_wave_1_1_wave_file_reader.html", [
          [ "NAudio.Wave.CueWaveFileReader", "class_n_audio_1_1_wave_1_1_cue_wave_file_reader.html", null ]
        ] ],
        [ "NAudio.Wave.WaveFormatConversionStream", "class_n_audio_1_1_wave_1_1_wave_format_conversion_stream.html", null ],
        [ "NAudio.Wave.WaveMixerStream32", "class_n_audio_1_1_wave_1_1_wave_mixer_stream32.html", null ],
        [ "NAudio.Wave.WaveOffsetStream", "class_n_audio_1_1_wave_1_1_wave_offset_stream.html", null ]
      ] ]
    ] ],
    [ "NAudio.Dmo.IWMResamplerProps", "interface_n_audio_1_1_dmo_1_1_i_w_m_resampler_props.html", null ],
    [ "xeno_rat_server.Listener", "classxeno__rat__server_1_1_listener.html", null ],
    [ "Plugin.Chromium.Login", "class_plugin_1_1_chromium_1_1_login.html", null ],
    [ "xeno_rat_server.Forms.Login", "classxeno__rat__server_1_1_forms_1_1_login.html", null ],
    [ "Plugin.Main", "class_plugin_1_1_main.html", null ],
    [ "NAudio.MediaFoundation.MediaFoundationApi", "class_n_audio_1_1_media_foundation_1_1_media_foundation_api.html", null ],
    [ "NAudio.MediaFoundation.MediaFoundationAttributes", "class_n_audio_1_1_media_foundation_1_1_media_foundation_attributes.html", null ],
    [ "NAudio.MediaFoundation.MediaFoundationErrors", "class_n_audio_1_1_media_foundation_1_1_media_foundation_errors.html", null ],
    [ "NAudio.MediaFoundation.MediaFoundationInterop", "class_n_audio_1_1_media_foundation_1_1_media_foundation_interop.html", null ],
    [ "NAudio.Wave.MediaFoundationReader.MediaFoundationReaderSettings", "class_n_audio_1_1_wave_1_1_media_foundation_reader_1_1_media_foundation_reader_settings.html", null ],
    [ "NAudio.MediaFoundation.MediaFoundationTransformCategories", "class_n_audio_1_1_media_foundation_1_1_media_foundation_transform_categories.html", null ],
    [ "NAudio.Dmo.MediaObjectSizeInfo", "class_n_audio_1_1_dmo_1_1_media_object_size_info.html", null ],
    [ "NAudio.Dmo.MediaParamInfo", "struct_n_audio_1_1_dmo_1_1_media_param_info.html", null ],
    [ "NAudio.MediaFoundation.MediaType", "class_n_audio_1_1_media_foundation_1_1_media_type.html", null ],
    [ "NAudio.Dmo.MediaTypes", "class_n_audio_1_1_dmo_1_1_media_types.html", null ],
    [ "NAudio.MediaFoundation.MediaTypes", "class_n_audio_1_1_media_foundation_1_1_media_types.html", null ],
    [ "NAudio.Utils.MergeSort", "class_n_audio_1_1_utils_1_1_merge_sort.html", null ],
    [ "NAudio.Mixer.MixerInterop.Metrics", "struct_n_audio_1_1_mixer_1_1_mixer_interop_1_1_metrics.html", null ],
    [ "NAudio.MediaFoundation.MF_SINK_WRITER_STATISTICS", "class_n_audio_1_1_media_foundation_1_1_m_f___s_i_n_k___w_r_i_t_e_r___s_t_a_t_i_s_t_i_c_s.html", null ],
    [ "NAudio.MediaFoundation.MFReadWriteClassFactory", "class_n_audio_1_1_media_foundation_1_1_m_f_read_write_class_factory.html", null ],
    [ "NAudio.MediaFoundation.MFT_INPUT_STREAM_INFO", "struct_n_audio_1_1_media_foundation_1_1_m_f_t___i_n_p_u_t___s_t_r_e_a_m___i_n_f_o.html", null ],
    [ "NAudio.MediaFoundation.MFT_OUTPUT_DATA_BUFFER", "struct_n_audio_1_1_media_foundation_1_1_m_f_t___o_u_t_p_u_t___d_a_t_a___b_u_f_f_e_r.html", null ],
    [ "NAudio.MediaFoundation.MFT_OUTPUT_STREAM_INFO", "struct_n_audio_1_1_media_foundation_1_1_m_f_t___o_u_t_p_u_t___s_t_r_e_a_m___i_n_f_o.html", null ],
    [ "NAudio.MediaFoundation.MFT_REGISTER_TYPE_INFO", "class_n_audio_1_1_media_foundation_1_1_m_f_t___r_e_g_i_s_t_e_r___t_y_p_e___i_n_f_o.html", null ],
    [ "NAudio.Midi.MidiInterop.MIDIEVENT", "struct_n_audio_1_1_midi_1_1_midi_interop_1_1_m_i_d_i_e_v_e_n_t.html", null ],
    [ "NAudio.Midi.MidiFile", "class_n_audio_1_1_midi_1_1_midi_file.html", null ],
    [ "NAudio.Midi.MidiInterop.MIDIHDR", "struct_n_audio_1_1_midi_1_1_midi_interop_1_1_m_i_d_i_h_d_r.html", null ],
    [ "NAudio.Midi.MidiInCapabilities", "struct_n_audio_1_1_midi_1_1_midi_in_capabilities.html", null ],
    [ "NAudio.Midi.MidiMessage", "class_n_audio_1_1_midi_1_1_midi_message.html", null ],
    [ "NAudio.Midi.MidiOutCapabilities", "struct_n_audio_1_1_midi_1_1_midi_out_capabilities.html", null ],
    [ "NAudio.Midi.MidiInterop.MIDIPROPTEMPO", "struct_n_audio_1_1_midi_1_1_midi_interop_1_1_m_i_d_i_p_r_o_p_t_e_m_p_o.html", null ],
    [ "NAudio.Mixer.Mixer", "class_n_audio_1_1_mixer_1_1_mixer.html", null ],
    [ "NAudio.Mixer.MixerInterop.MIXERCAPS", "struct_n_audio_1_1_mixer_1_1_mixer_interop_1_1_m_i_x_e_r_c_a_p_s.html", null ],
    [ "NAudio.Mixer.MixerControl", "class_n_audio_1_1_mixer_1_1_mixer_control.html", [
      [ "NAudio.Mixer.BooleanMixerControl", "class_n_audio_1_1_mixer_1_1_boolean_mixer_control.html", null ],
      [ "NAudio.Mixer.CustomMixerControl", "class_n_audio_1_1_mixer_1_1_custom_mixer_control.html", null ],
      [ "NAudio.Mixer.ListTextMixerControl", "class_n_audio_1_1_mixer_1_1_list_text_mixer_control.html", null ],
      [ "NAudio.Mixer.SignedMixerControl", "class_n_audio_1_1_mixer_1_1_signed_mixer_control.html", null ],
      [ "NAudio.Mixer.UnsignedMixerControl", "class_n_audio_1_1_mixer_1_1_unsigned_mixer_control.html", null ]
    ] ],
    [ "NAudio.Mixer.MixerInterop.MIXERCONTROL", "struct_n_audio_1_1_mixer_1_1_mixer_interop_1_1_m_i_x_e_r_c_o_n_t_r_o_l.html", null ],
    [ "NAudio.Mixer.MixerInterop.MIXERCONTROLDETAILS", "struct_n_audio_1_1_mixer_1_1_mixer_interop_1_1_m_i_x_e_r_c_o_n_t_r_o_l_d_e_t_a_i_l_s.html", null ],
    [ "NAudio.Mixer.MixerInterop.MIXERCONTROLDETAILS_BOOLEAN", "struct_n_audio_1_1_mixer_1_1_mixer_interop_1_1_m_i_x_e_r_c_o_n_t_r_o_l_d_e_t_a_i_l_s___b_o_o_l_e_a_n.html", null ],
    [ "NAudio.Mixer.MixerInterop.MIXERCONTROLDETAILS_LISTTEXT", "struct_n_audio_1_1_mixer_1_1_mixer_interop_1_1_m_i_x_e_r_c_o_n_t_r_o_l_d_e_t_a_i_l_s___l_i_s_t_t_e_x_t.html", null ],
    [ "NAudio.Mixer.MixerInterop.MIXERCONTROLDETAILS_SIGNED", "struct_n_audio_1_1_mixer_1_1_mixer_interop_1_1_m_i_x_e_r_c_o_n_t_r_o_l_d_e_t_a_i_l_s___s_i_g_n_e_d.html", null ],
    [ "NAudio.Mixer.MixerInterop.MIXERCONTROLDETAILS_UNSIGNED", "struct_n_audio_1_1_mixer_1_1_mixer_interop_1_1_m_i_x_e_r_c_o_n_t_r_o_l_d_e_t_a_i_l_s___u_n_s_i_g_n_e_d.html", null ],
    [ "NAudio.Mixer.MixerInterop", "class_n_audio_1_1_mixer_1_1_mixer_interop.html", null ],
    [ "NAudio.Mixer.MixerInterop.MIXERLINE", "struct_n_audio_1_1_mixer_1_1_mixer_interop_1_1_m_i_x_e_r_l_i_n_e.html", null ],
    [ "NAudio.Mixer.MixerLine", "class_n_audio_1_1_mixer_1_1_mixer_line.html", null ],
    [ "NAudio.Mixer.MixerInterop.MIXERLINECONTROLS", "struct_n_audio_1_1_mixer_1_1_mixer_interop_1_1_m_i_x_e_r_l_i_n_e_c_o_n_t_r_o_l_s.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.MMDeviceEnumeratorComObject", "class_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_m_m_device_enumerator_com_object.html", null ],
    [ "Plugin.MMDeviceEnumeratorComObject", "class_plugin_1_1_m_m_device_enumerator_com_object.html", null ],
    [ "NAudio.Midi.MidiInterop.MMTIME", "struct_n_audio_1_1_midi_1_1_midi_interop_1_1_m_m_t_i_m_e.html", null ],
    [ "NAudio.Wave.MmTime", "struct_n_audio_1_1_wave_1_1_mm_time.html", null ],
    [ "NAudio.SoundFont.Modulator", "class_n_audio_1_1_sound_font_1_1_modulator.html", null ],
    [ "NAudio.SoundFont.ModulatorBuilder", "class_n_audio_1_1_sound_font_1_1_modulator_builder.html", null ],
    [ "NAudio.SoundFont.ModulatorType", "class_n_audio_1_1_sound_font_1_1_modulator_type.html", null ],
    [ "NAudio.Wave.Mp3Frame", "class_n_audio_1_1_wave_1_1_mp3_frame.html", null ],
    [ "NAudio.Wave.Mp3Index", "class_n_audio_1_1_wave_1_1_mp3_index.html", null ],
    [ "NAudio.Codecs.MuLawDecoder", "class_n_audio_1_1_codecs_1_1_mu_law_decoder.html", null ],
    [ "NAudio.Codecs.MuLawEncoder", "class_n_audio_1_1_codecs_1_1_mu_law_encoder.html", null ],
    [ "NAudio.Utils.NativeMethods", "class_n_audio_1_1_utils_1_1_native_methods.html", null ],
    [ "NAudio.Wasapi.CoreAudioApi.NativeMethods", "class_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_native_methods.html", null ],
    [ "xeno_rat_server.IconInjector.NativeMethods", "classxeno__rat__server_1_1_icon_injector_1_1_native_methods.html", null ],
    [ "NativeWindow", "class_native_window.html", [
      [ "NAudio.Wave.WaveWindowNative", "class_n_audio_1_1_wave_1_1_wave_window_native.html", null ]
    ] ],
    [ "xeno_rat_client.Node", "classxeno__rat__client_1_1_node.html", null ],
    [ "xeno_rat_server.Node", "classxeno__rat__server_1_1_node.html", null ],
    [ "NAudio.Dmo.Effect.DmoChorus.Params", "struct_n_audio_1_1_dmo_1_1_effect_1_1_dmo_chorus_1_1_params.html", null ],
    [ "NAudio.Dmo.Effect.DmoCompressor.Params", "struct_n_audio_1_1_dmo_1_1_effect_1_1_dmo_compressor_1_1_params.html", null ],
    [ "NAudio.Dmo.Effect.DmoDistortion.Params", "struct_n_audio_1_1_dmo_1_1_effect_1_1_dmo_distortion_1_1_params.html", null ],
    [ "NAudio.Dmo.Effect.DmoEcho.Params", "struct_n_audio_1_1_dmo_1_1_effect_1_1_dmo_echo_1_1_params.html", null ],
    [ "NAudio.Dmo.Effect.DmoFlanger.Params", "struct_n_audio_1_1_dmo_1_1_effect_1_1_dmo_flanger_1_1_params.html", null ],
    [ "NAudio.Dmo.Effect.DmoGargle.Params", "struct_n_audio_1_1_dmo_1_1_effect_1_1_dmo_gargle_1_1_params.html", null ],
    [ "NAudio.Dmo.Effect.DmoI3DL2Reverb.Params", "struct_n_audio_1_1_dmo_1_1_effect_1_1_dmo_i3_d_l2_reverb_1_1_params.html", null ],
    [ "NAudio.Dmo.Effect.DmoParamEq.Params", "struct_n_audio_1_1_dmo_1_1_effect_1_1_dmo_param_eq_1_1_params.html", null ],
    [ "NAudio.Dmo.Effect.DmoWavesReverb.Params", "struct_n_audio_1_1_dmo_1_1_effect_1_1_dmo_waves_reverb_1_1_params.html", null ],
    [ "PictureBox", "class_picture_box.html", [
      [ "xeno_rat_server.Forms.CustomPictureBox", "classxeno__rat__server_1_1_forms_1_1_custom_picture_box.html", null ]
    ] ],
    [ "Hidden_handler.input_handler.POINT", "struct_hidden__handler_1_1input__handler_1_1_p_o_i_n_t.html", null ],
    [ "Plugin.ScreenshotTaker.POINTAPI", "struct_plugin_1_1_screenshot_taker_1_1_p_o_i_n_t_a_p_i.html", null ],
    [ "NAudio.SoundFont.Preset", "class_n_audio_1_1_sound_font_1_1_preset.html", null ],
    [ "NAudio.SoundFont.PresetBuilder", "class_n_audio_1_1_sound_font_1_1_preset_builder.html", null ],
    [ "NAudio.SoundFont.PresetsChunk", "class_n_audio_1_1_sound_font_1_1_presets_chunk.html", null ],
    [ "Hidden_handler.Process_Handler", "class_hidden__handler_1_1_process___handler.html", null ],
    [ "Hidden_handler._ProcessHelper.PROCESS_INFORMATION", "struct_hidden__handler_1_1___process_helper_1_1_p_r_o_c_e_s_s___i_n_f_o_r_m_a_t_i_o_n.html", null ],
    [ "Plugin.Main.PROCESSENTRY32", "struct_plugin_1_1_main_1_1_p_r_o_c_e_s_s_e_n_t_r_y32.html", null ],
    [ "Plugin.Main.ProcessNode", "class_plugin_1_1_main_1_1_process_node.html", null ],
    [ "xeno_rat_server.Forms.ProcessNode", "classxeno__rat__server_1_1_forms_1_1_process_node.html", null ],
    [ "xeno_rat_client.Program", "classxeno__rat__client_1_1_program.html", null ],
    [ "xeno_rat_server.Program", "classxeno__rat__server_1_1_program.html", null ],
    [ "NAudio.CoreAudioApi.PropertyKey", "struct_n_audio_1_1_core_audio_api_1_1_property_key.html", null ],
    [ "NAudio.CoreAudioApi.PropertyKeys", "class_n_audio_1_1_core_audio_api_1_1_property_keys.html", null ],
    [ "NAudio.CoreAudioApi.PropertyStore", "class_n_audio_1_1_core_audio_api_1_1_property_store.html", null ],
    [ "NAudio.CoreAudioApi.PropertyStoreProperty", "class_n_audio_1_1_core_audio_api_1_1_property_store_property.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.PropVariant", "struct_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_prop_variant.html", null ],
    [ "NAudio.CoreAudioApi.Interfaces.PropVariantNative", "class_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_prop_variant_native.html", null ],
    [ "InfoGrab.SQLiteHandler.record_header_field", "struct_info_grab_1_1_s_q_lite_handler_1_1record__header__field.html", null ],
    [ "Hidden_handler.Imaging_handler.RECT", "struct_hidden__handler_1_1_imaging__handler_1_1_r_e_c_t.html", null ],
    [ "Hidden_handler.input_handler.RECT", "struct_hidden__handler_1_1input__handler_1_1_r_e_c_t.html", null ],
    [ "Plugin.RegInfo", "class_plugin_1_1_reg_info.html", null ],
    [ "xeno_rat_server.Forms.RegInfo", "classxeno__rat__server_1_1_forms_1_1_reg_info.html", null ],
    [ "Plugin.RegValue", "class_plugin_1_1_reg_value.html", null ],
    [ "xeno_rat_server.Forms.RegValue", "classxeno__rat__server_1_1_forms_1_1_reg_value.html", null ],
    [ "xeno_rat_server.Forms.Socks5Const.Reply", "classxeno__rat__server_1_1_forms_1_1_socks5_const_1_1_reply.html", null ],
    [ "NAudio.Dmo.ResamplerMediaComObject", "class_n_audio_1_1_dmo_1_1_resampler_media_com_object.html", null ],
    [ "NAudio.Wave.RiffChunk", "class_n_audio_1_1_wave_1_1_riff_chunk.html", null ],
    [ "NAudio.SoundFont.SampleDataChunk", "class_n_audio_1_1_sound_font_1_1_sample_data_chunk.html", null ],
    [ "NAudio.SoundFont.SampleHeader", "class_n_audio_1_1_sound_font_1_1_sample_header.html", null ],
    [ "NAudio.SoundFont.SampleHeaderBuilder", "class_n_audio_1_1_sound_font_1_1_sample_header_builder.html", null ],
    [ "NAudio.Wave.SampleProviders.SampleProviderConverters", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_converters.html", null ],
    [ "Plugin.ScreenshotTaker", "class_plugin_1_1_screenshot_taker.html", null ],
    [ "NAudio.CoreAudioApi.SessionCollection", "class_n_audio_1_1_core_audio_api_1_1_session_collection.html", null ],
    [ "NAudio.SoundFont.SFVersion", "class_n_audio_1_1_sound_font_1_1_s_f_version.html", null ],
    [ "NAudio.SoundFont.SFVersionBuilder", "class_n_audio_1_1_sound_font_1_1_s_f_version_builder.html", null ],
    [ "Hidden_handler._ProcessHelper.SID_AND_ATTRIBUTES", "struct_hidden__handler_1_1___process_helper_1_1_s_i_d___a_n_d___a_t_t_r_i_b_u_t_e_s.html", null ],
    [ "NAudio.Dsp.SmbPitchShifter", "class_n_audio_1_1_dsp_1_1_smb_pitch_shifter.html", null ],
    [ "xeno_rat_client.SocketHandler", "classxeno__rat__client_1_1_socket_handler.html", null ],
    [ "xeno_rat_server.SocketHandler", "classxeno__rat__server_1_1_socket_handler.html", null ],
    [ "Plugin.Socks5Const", "class_plugin_1_1_socks5_const.html", null ],
    [ "xeno_rat_server.Forms.Socks5Const", "classxeno__rat__server_1_1_forms_1_1_socks5_const.html", null ],
    [ "Plugin.Socks5Handler", "class_plugin_1_1_socks5_handler.html", null ],
    [ "NAudio.SoundFont.SoundFont", "class_n_audio_1_1_sound_font_1_1_sound_font.html", null ],
    [ "InfoGrab.SQLiteHandler.sqlite_master_entry", "struct_info_grab_1_1_s_q_lite_handler_1_1sqlite__master__entry.html", null ],
    [ "InfoGrab.SQLiteHandler", "class_info_grab_1_1_s_q_lite_handler.html", null ],
    [ "Hidden_handler._ProcessHelper.STARTUPINFO", "struct_hidden__handler_1_1___process_helper_1_1_s_t_a_r_t_u_p_i_n_f_o.html", null ],
    [ "Hidden_handler.Process_Handler.STARTUPINFO", "struct_hidden__handler_1_1_process___handler_1_1_s_t_a_r_t_u_p_i_n_f_o.html", null ],
    [ "NAudio.Wave.SampleProviders.StereoSamplePair", "struct_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_sample_pair.html", null ],
    [ "Plugin.SystemUtility", "class_plugin_1_1_system_utility.html", null ],
    [ "InfoGrab.SQLiteHandler.table_entry", "struct_info_grab_1_1_s_q_lite_handler_1_1table__entry.html", null ],
    [ "TextWriter", "class_text_writer.html", [
      [ "xeno_rat_client.CapturingConsoleWriter", "classxeno__rat__client_1_1_capturing_console_writer.html", null ]
    ] ],
    [ "Hidden_handler._ProcessHelper.TOKEN_MANDATORY_LABEL", "struct_hidden__handler_1_1___process_helper_1_1_t_o_k_e_n___m_a_n_d_a_t_o_r_y___l_a_b_e_l.html", null ],
    [ "NAudio.MediaFoundation.TranscodeContainerTypes", "class_n_audio_1_1_media_foundation_1_1_transcode_container_types.html", null ],
    [ "xeno_rat_client.Utils", "classxeno__rat__client_1_1_utils.html", null ],
    [ "xeno_rat_server.Utils", "classxeno__rat__server_1_1_utils.html", null ],
    [ "AForge.Video.DirectShow.VideoCapabilities", "class_a_forge_1_1_video_1_1_direct_show_1_1_video_capabilities.html", null ],
    [ "AForge.Video.DirectShow.VideoInput", "class_a_forge_1_1_video_1_1_direct_show_1_1_video_input.html", null ],
    [ "NAudio.Wave.WaveCallbackInfo", "class_n_audio_1_1_wave_1_1_wave_callback_info.html", null ],
    [ "NAudio.Wave.WaveCapabilitiesHelpers", "class_n_audio_1_1_wave_1_1_wave_capabilities_helpers.html", null ],
    [ "NAudio.Wave.WaveExtensionMethods", "class_n_audio_1_1_wave_1_1_wave_extension_methods.html", null ],
    [ "NAudio.FileFormats.Wav.WaveFileChunkReader", "class_n_audio_1_1_file_formats_1_1_wav_1_1_wave_file_chunk_reader.html", null ],
    [ "NAudio.Wave.Compression.WaveFilter", "class_n_audio_1_1_wave_1_1_compression_1_1_wave_filter.html", null ],
    [ "NAudio.Wave.WaveFormat", "class_n_audio_1_1_wave_1_1_wave_format.html", [
      [ "NAudio.Wave.AdpcmWaveFormat", "class_n_audio_1_1_wave_1_1_adpcm_wave_format.html", null ],
      [ "NAudio.Wave.Gsm610WaveFormat", "class_n_audio_1_1_wave_1_1_gsm610_wave_format.html", null ],
      [ "NAudio.Wave.ImaAdpcmWaveFormat", "class_n_audio_1_1_wave_1_1_ima_adpcm_wave_format.html", null ],
      [ "NAudio.Wave.Mp3WaveFormat", "class_n_audio_1_1_wave_1_1_mp3_wave_format.html", null ],
      [ "NAudio.Wave.OggWaveFormat", "class_n_audio_1_1_wave_1_1_ogg_wave_format.html", null ],
      [ "NAudio.Wave.TrueSpeechWaveFormat", "class_n_audio_1_1_wave_1_1_true_speech_wave_format.html", null ],
      [ "NAudio.Wave.WaveFormatExtensible", "class_n_audio_1_1_wave_1_1_wave_format_extensible.html", null ],
      [ "NAudio.Wave.WaveFormatExtraData", "class_n_audio_1_1_wave_1_1_wave_format_extra_data.html", null ],
      [ "NAudio.Wave.WaveFormats.WmaWaveFormat", "class_n_audio_1_1_wave_1_1_wave_formats_1_1_wma_wave_format.html", null ]
    ] ],
    [ "NAudio.Wave.WaveHeader", "class_n_audio_1_1_wave_1_1_wave_header.html", null ],
    [ "NAudio.Wave.WaveInCapabilities", "struct_n_audio_1_1_wave_1_1_wave_in_capabilities.html", null ],
    [ "NAudio.Wave.WaveInterop", "class_n_audio_1_1_wave_1_1_wave_interop.html", null ],
    [ "NAudio.Wave.WaveOutCapabilities", "struct_n_audio_1_1_wave_1_1_wave_out_capabilities.html", null ],
    [ "NAudio.Wave.WaveOutUtils", "class_n_audio_1_1_wave_1_1_wave_out_utils.html", null ],
    [ "NAudio.Utils.WavePositionExtensions", "class_n_audio_1_1_utils_1_1_wave_position_extensions.html", null ],
    [ "NAudio.Dsp.WdlResampler.WDL_Resampler_IIRFilter", "class_n_audio_1_1_dsp_1_1_wdl_resampler_1_1_w_d_l___resampler___i_i_r_filter.html", null ],
    [ "NAudio.Dsp.WdlResampler", "class_n_audio_1_1_dsp_1_1_wdl_resampler.html", null ],
    [ "Plugin.Chromium.WebHistory", "class_plugin_1_1_chromium_1_1_web_history.html", null ],
    [ "xeno_rat_server.Forms.WebHistory", "classxeno__rat__server_1_1_forms_1_1_web_history.html", null ],
    [ "Hidden_handler.input_handler.WINDOWPLACEMENT", "struct_hidden__handler_1_1input__handler_1_1_w_i_n_d_o_w_p_l_a_c_e_m_e_n_t.html", null ],
    [ "NAudio.Dmo.WindowsMediaMp3DecoderComObject", "class_n_audio_1_1_dmo_1_1_windows_media_mp3_decoder_com_object.html", null ],
    [ "NAudio.Wave.XingHeader", "class_n_audio_1_1_wave_1_1_xing_header.html", null ],
    [ "NAudio.SoundFont.Zone", "class_n_audio_1_1_sound_font_1_1_zone.html", null ],
    [ "NAudio.SoundFont.ZoneBuilder", "class_n_audio_1_1_sound_font_1_1_zone_builder.html", null ],
    [ "Stream", null, [
      [ "NAudio.Utils.IgnoreDisposeStream", "class_n_audio_1_1_utils_1_1_ignore_dispose_stream.html", null ],
      [ "NAudio.Wave.AiffFileWriter", "class_n_audio_1_1_wave_1_1_aiff_file_writer.html", null ],
      [ "NAudio.Wave.ComStream", "class_n_audio_1_1_wave_1_1_com_stream.html", null ],
      [ "NAudio.Wave.WaveFileWriter", "class_n_audio_1_1_wave_1_1_wave_file_writer.html", [
        [ "NAudio.Wave.CueWaveFileWriter", "class_n_audio_1_1_wave_1_1_cue_wave_file_writer.html", null ]
      ] ],
      [ "NAudio.Wave.WaveStream", "class_n_audio_1_1_wave_1_1_wave_stream.html", null ]
    ] ]
];