var namespace_n_audio_1_1_wave_1_1_sample_providers =
[
    [ "AdsrSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_adsr_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_adsr_sample_provider" ],
    [ "ConcatenatingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_concatenating_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_concatenating_sample_provider" ],
    [ "FadeInOutSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_fade_in_out_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_fade_in_out_sample_provider" ],
    [ "IPanStrategy", "interface_n_audio_1_1_wave_1_1_sample_providers_1_1_i_pan_strategy.html", "interface_n_audio_1_1_wave_1_1_sample_providers_1_1_i_pan_strategy" ],
    [ "ISampleChunkConverter", "interface_n_audio_1_1_wave_1_1_sample_providers_1_1_i_sample_chunk_converter.html", "interface_n_audio_1_1_wave_1_1_sample_providers_1_1_i_sample_chunk_converter" ],
    [ "LinearPanStrategy", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_linear_pan_strategy.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_linear_pan_strategy" ],
    [ "MeteringSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_metering_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_metering_sample_provider" ],
    [ "MixingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mixing_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mixing_sample_provider" ],
    [ "Mono16SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono16_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono16_sample_chunk_converter" ],
    [ "Mono24SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono24_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono24_sample_chunk_converter" ],
    [ "Mono8SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono8_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono8_sample_chunk_converter" ],
    [ "MonoFloatSampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono_float_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono_float_sample_chunk_converter" ],
    [ "MonoToStereoSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono_to_stereo_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_mono_to_stereo_sample_provider" ],
    [ "MultiplexingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_multiplexing_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_multiplexing_sample_provider" ],
    [ "NotifyingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_notifying_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_notifying_sample_provider" ],
    [ "OffsetSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_offset_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_offset_sample_provider" ],
    [ "PanningSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_panning_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_panning_sample_provider" ],
    [ "Pcm16BitToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm16_bit_to_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm16_bit_to_sample_provider" ],
    [ "Pcm24BitToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm24_bit_to_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm24_bit_to_sample_provider" ],
    [ "Pcm32BitToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm32_bit_to_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm32_bit_to_sample_provider" ],
    [ "Pcm8BitToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm8_bit_to_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_pcm8_bit_to_sample_provider" ],
    [ "SampleChannel", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_channel.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_channel" ],
    [ "SampleProviderConverterBase", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_converter_base.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_converter_base" ],
    [ "SampleProviderConverters", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_converters.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_converters" ],
    [ "SampleProviderEventArgs", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_event_args.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_provider_event_args" ],
    [ "SampleToWaveProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider" ],
    [ "SampleToWaveProvider16", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider16.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider16" ],
    [ "SampleToWaveProvider24", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider24.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sample_to_wave_provider24" ],
    [ "SignalGenerator", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_signal_generator.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_signal_generator" ],
    [ "SinPanStrategy", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sin_pan_strategy.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_sin_pan_strategy" ],
    [ "SmbPitchShiftingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_smb_pitch_shifting_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_smb_pitch_shifting_sample_provider" ],
    [ "SquareRootPanStrategy", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_square_root_pan_strategy.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_square_root_pan_strategy" ],
    [ "Stereo16SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo16_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo16_sample_chunk_converter" ],
    [ "Stereo24SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo24_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo24_sample_chunk_converter" ],
    [ "Stereo8SampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo8_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo8_sample_chunk_converter" ],
    [ "StereoBalanceStrategy", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_balance_strategy.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_balance_strategy" ],
    [ "StereoFloatSampleChunkConverter", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_float_sample_chunk_converter.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_float_sample_chunk_converter" ],
    [ "StereoSamplePair", "struct_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_sample_pair.html", "struct_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_sample_pair" ],
    [ "StereoToMonoSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_to_mono_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stereo_to_mono_sample_provider" ],
    [ "StreamVolumeEventArgs", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stream_volume_event_args.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_stream_volume_event_args" ],
    [ "VolumeSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_volume_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_volume_sample_provider" ],
    [ "WaveToSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wave_to_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wave_to_sample_provider" ],
    [ "WaveToSampleProvider64", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wave_to_sample_provider64.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wave_to_sample_provider64" ],
    [ "WdlResamplingSampleProvider", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wdl_resampling_sample_provider.html", "class_n_audio_1_1_wave_1_1_sample_providers_1_1_wdl_resampling_sample_provider" ],
    [ "SignalGeneratorType", "namespace_n_audio_1_1_wave_1_1_sample_providers.html#af7ad5a09d5f7501bd001385f5590d093", [
      [ "Pink", "namespace_n_audio_1_1_wave_1_1_sample_providers.html#af7ad5a09d5f7501bd001385f5590d093a8dc5344bc0746e1cc5abf896ca03bbdf", null ],
      [ "White", "namespace_n_audio_1_1_wave_1_1_sample_providers.html#af7ad5a09d5f7501bd001385f5590d093a25a81701fbfa4a1efdf660a950c1d006", null ],
      [ "Sweep", "namespace_n_audio_1_1_wave_1_1_sample_providers.html#af7ad5a09d5f7501bd001385f5590d093a8e9014ddfce21beb1b3cd7da888cbdea", null ],
      [ "Sin", "namespace_n_audio_1_1_wave_1_1_sample_providers.html#af7ad5a09d5f7501bd001385f5590d093a0986d137604183312e6d3599578bc6cd", null ],
      [ "Square", "namespace_n_audio_1_1_wave_1_1_sample_providers.html#af7ad5a09d5f7501bd001385f5590d093aceb46ca115d05c51aa5a16a8867c3304", null ],
      [ "Triangle", "namespace_n_audio_1_1_wave_1_1_sample_providers.html#af7ad5a09d5f7501bd001385f5590d093a5e5500cb2b82eb72d550de644bd1b64b", null ],
      [ "SawTooth", "namespace_n_audio_1_1_wave_1_1_sample_providers.html#af7ad5a09d5f7501bd001385f5590d093ac29116adf3462ee05d52ef986502e64e", null ]
    ] ]
];