var searchData=
[
  ['iactivateaudiointerfaceasyncoperation_0',['IActivateAudioInterfaceAsyncOperation',['../interface_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_interfaces_1_1_i_activate_audio_interface_async_operation.html',1,'NAudio::Wasapi::CoreAudioApi::Interfaces']]],
  ['iactivateaudiointerfacecompletionhandler_1',['IActivateAudioInterfaceCompletionHandler',['../interface_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_interfaces_1_1_i_activate_audio_interface_completion_handler.html',1,'NAudio::Wasapi::CoreAudioApi::Interfaces']]],
  ['iagileobject_2',['IAgileObject',['../interface_n_audio_1_1_wasapi_1_1_core_audio_api_1_1_interfaces_1_1_i_agile_object.html',1,'NAudio::Wasapi::CoreAudioApi::Interfaces']]],
  ['iaudiocaptureclient_3',['IAudioCaptureClient',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_capture_client.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['iaudioclient_4',['IAudioClient',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_client.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['iaudioclient2_5',['IAudioClient2',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_client2.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['iaudioendpointvolume_6',['IAudioEndpointVolume',['../interface_plugin_1_1_i_audio_endpoint_volume.html',1,'Plugin']]],
  ['iaudiorenderclient_7',['IAudioRenderClient',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_render_client.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['iaudiosessioncontrol_8',['IAudioSessionControl',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_control.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['iaudiosessioncontrol2_9',['IAudioSessionControl2',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_control2.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['iaudiosessionevents_10',['IAudioSessionEvents',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_events.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['iaudiosessioneventshandler_11',['IAudioSessionEventsHandler',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_events_handler.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['iaudiosessionnotification_12',['IAudioSessionNotification',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_session_notification.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['iaudiostreamvolume_13',['IAudioStreamVolume',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_audio_stream_volume.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['icloneable_14',['ICloneable',['../class_i_cloneable.html',1,'']]],
  ['icomparable_15',['IComparable',['../class_i_comparable.html',1,'']]],
  ['icomparer_16',['IComparer',['../class_i_comparer.html',1,'']]],
  ['icondir_17',['ICONDIR',['../structxeno__rat__server_1_1_icon_injector_1_1_i_c_o_n_d_i_r.html',1,'xeno_rat_server::IconInjector']]],
  ['icondirentry_18',['ICONDIRENTRY',['../structxeno__rat__server_1_1_icon_injector_1_1_i_c_o_n_d_i_r_e_n_t_r_y.html',1,'xeno_rat_server::IconInjector']]],
  ['iconfile_19',['IconFile',['../classxeno__rat__server_1_1_icon_injector_1_1_icon_file.html',1,'xeno_rat_server::IconInjector']]],
  ['iconinjector_20',['IconInjector',['../classxeno__rat__server_1_1_icon_injector.html',1,'xeno_rat_server']]],
  ['icustommarshaler_21',['ICustomMarshaler',['../class_i_custom_marshaler.html',1,'']]],
  ['id3v2tag_22',['Id3v2Tag',['../class_n_audio_1_1_wave_1_1_id3v2_tag.html',1,'NAudio::Wave']]],
  ['idirectsoundfxcompressor_23',['IDirectSoundFXCompressor',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_compressor.html',1,'NAudio::Dmo::Effect']]],
  ['idirectsoundfxdistortion_24',['IDirectSoundFXDistortion',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_distortion.html',1,'NAudio::Dmo::Effect']]],
  ['idirectsoundfxecho_25',['IDirectSoundFXEcho',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_echo.html',1,'NAudio::Dmo::Effect']]],
  ['idirectsoundfxflanger_26',['IDirectSoundFXFlanger',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_flanger.html',1,'NAudio::Dmo::Effect']]],
  ['idirectsoundfxgargle_27',['IDirectSoundFXGargle',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_gargle.html',1,'NAudio::Dmo::Effect']]],
  ['idirectsoundfxi3dl2reverb_28',['IDirectSoundFXI3DL2Reverb',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_i3_d_l2_reverb.html',1,'NAudio::Dmo::Effect']]],
  ['idirectsoundfxparameq_29',['IDirectSoundFxParamEq',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_fx_param_eq.html',1,'NAudio::Dmo::Effect']]],
  ['idirectsoundfxwavesreverb_30',['IDirectSoundFXWavesReverb',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_direct_sound_f_x_waves_reverb.html',1,'NAudio::Dmo::Effect']]],
  ['idispatch_31',['IDispatch',['../interface_plugin_1_1_system_utility_1_1_i_dispatch.html',1,'Plugin::SystemUtility']]],
  ['idisposable_32',['IDisposable',['../class_i_disposable.html',1,'']]],
  ['idmoeffector_33',['IDmoEffector',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html',1,'NAudio::Dmo::Effect']]],
  ['idmoeffector_3c_20dmochorus_2eparams_20_3e_34',['IDmoEffector&lt; DmoChorus.Params &gt;',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html',1,'NAudio::Dmo::Effect']]],
  ['idmoeffector_3c_20dmocompressor_2eparams_20_3e_35',['IDmoEffector&lt; DmoCompressor.Params &gt;',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html',1,'NAudio::Dmo::Effect']]],
  ['idmoeffector_3c_20dmodistortion_2eparams_20_3e_36',['IDmoEffector&lt; DmoDistortion.Params &gt;',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html',1,'NAudio::Dmo::Effect']]],
  ['idmoeffector_3c_20dmoecho_2eparams_20_3e_37',['IDmoEffector&lt; DmoEcho.Params &gt;',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html',1,'NAudio::Dmo::Effect']]],
  ['idmoeffector_3c_20dmoflanger_2eparams_20_3e_38',['IDmoEffector&lt; DmoFlanger.Params &gt;',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html',1,'NAudio::Dmo::Effect']]],
  ['idmoeffector_3c_20dmogargle_2eparams_20_3e_39',['IDmoEffector&lt; DmoGargle.Params &gt;',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html',1,'NAudio::Dmo::Effect']]],
  ['idmoeffector_3c_20dmoi3dl2reverb_2eparams_20_3e_40',['IDmoEffector&lt; DmoI3DL2Reverb.Params &gt;',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html',1,'NAudio::Dmo::Effect']]],
  ['idmoeffector_3c_20dmoparameq_2eparams_20_3e_41',['IDmoEffector&lt; DmoParamEq.Params &gt;',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html',1,'NAudio::Dmo::Effect']]],
  ['idmoeffector_3c_20dmowavesreverb_2eparams_20_3e_42',['IDmoEffector&lt; DmoWavesReverb.Params &gt;',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html',1,'NAudio::Dmo::Effect']]],
  ['idmoeffector_3c_20teffectorparam_20_3e_43',['IDmoEffector&lt; TEffectorParam &gt;',['../interface_n_audio_1_1_dmo_1_1_effect_1_1_i_dmo_effector.html',1,'NAudio::Dmo::Effect']]],
  ['ieee_44',['IEEE',['../class_n_audio_1_1_utils_1_1_i_e_e_e.html',1,'NAudio::Utils']]],
  ['ienumdmo_45',['IEnumDmo',['../interface_n_audio_1_1_dmo_1_1_i_enum_dmo.html',1,'NAudio::Dmo']]],
  ['ienumerable_46',['IEnumerable',['../class_i_enumerable.html',1,'']]],
  ['ignoredisposestream_47',['IgnoreDisposeStream',['../class_n_audio_1_1_utils_1_1_ignore_dispose_stream.html',1,'NAudio::Utils']]],
  ['imaadpcmwaveformat_48',['ImaAdpcmWaveFormat',['../class_n_audio_1_1_wave_1_1_ima_adpcm_wave_format.html',1,'NAudio::Wave']]],
  ['imaging_5fhandler_49',['Imaging_handler',['../class_hidden__handler_1_1_imaging__handler.html',1,'Hidden_handler']]],
  ['imediabuffer_50',['IMediaBuffer',['../interface_n_audio_1_1_dmo_1_1_i_media_buffer.html',1,'NAudio::Dmo']]],
  ['imediaobject_51',['IMediaObject',['../interface_n_audio_1_1_dmo_1_1_i_media_object.html',1,'NAudio::Dmo']]],
  ['imediaparaminfo_52',['IMediaParamInfo',['../interface_n_audio_1_1_dmo_1_1_i_media_param_info.html',1,'NAudio::Dmo']]],
  ['imfactivate_53',['IMFActivate',['../interface_n_audio_1_1_media_foundation_1_1_i_m_f_activate.html',1,'NAudio::MediaFoundation']]],
  ['imfattributes_54',['IMFAttributes',['../interface_n_audio_1_1_media_foundation_1_1_i_m_f_attributes.html',1,'NAudio::MediaFoundation']]],
  ['imfbytestream_55',['IMFByteStream',['../interface_n_audio_1_1_media_foundation_1_1_i_m_f_byte_stream.html',1,'NAudio::MediaFoundation']]],
  ['imfcollection_56',['IMFCollection',['../interface_n_audio_1_1_media_foundation_1_1_i_m_f_collection.html',1,'NAudio::MediaFoundation']]],
  ['imfmediabuffer_57',['IMFMediaBuffer',['../interface_n_audio_1_1_media_foundation_1_1_i_m_f_media_buffer.html',1,'NAudio::MediaFoundation']]],
  ['imfmediaevent_58',['IMFMediaEvent',['../interface_n_audio_1_1_media_foundation_1_1_i_m_f_media_event.html',1,'NAudio::MediaFoundation']]],
  ['imfmediatype_59',['IMFMediaType',['../interface_n_audio_1_1_media_foundation_1_1_i_m_f_media_type.html',1,'NAudio::MediaFoundation']]],
  ['imfreadwriteclassfactory_60',['IMFReadWriteClassFactory',['../interface_n_audio_1_1_media_foundation_1_1_i_m_f_read_write_class_factory.html',1,'NAudio::MediaFoundation']]],
  ['imfsample_61',['IMFSample',['../interface_n_audio_1_1_media_foundation_1_1_i_m_f_sample.html',1,'NAudio::MediaFoundation']]],
  ['imfsinkwriter_62',['IMFSinkWriter',['../interface_n_audio_1_1_media_foundation_1_1_i_m_f_sink_writer.html',1,'NAudio::MediaFoundation']]],
  ['imfsourcereader_63',['IMFSourceReader',['../interface_n_audio_1_1_media_foundation_1_1_i_m_f_source_reader.html',1,'NAudio::MediaFoundation']]],
  ['imftransform_64',['IMFTransform',['../interface_n_audio_1_1_media_foundation_1_1_i_m_f_transform.html',1,'NAudio::MediaFoundation']]],
  ['immdevice_65',['IMMDevice',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_device.html',1,'NAudio.CoreAudioApi.Interfaces.IMMDevice'],['../interface_plugin_1_1_i_m_m_device.html',1,'Plugin.IMMDevice']]],
  ['immdevicecollection_66',['IMMDeviceCollection',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_device_collection.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['immdeviceenumerator_67',['IMMDeviceEnumerator',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_device_enumerator.html',1,'NAudio.CoreAudioApi.Interfaces.IMMDeviceEnumerator'],['../interface_plugin_1_1_i_m_m_device_enumerator.html',1,'Plugin.IMMDeviceEnumerator']]],
  ['immendpoint_68',['IMMEndpoint',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_endpoint.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['immnotificationclient_69',['IMMNotificationClient',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_m_m_notification_client.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['imp3framedecompressor_70',['IMp3FrameDecompressor',['../interface_n_audio_1_1_wave_1_1_i_mp3_frame_decompressor.html',1,'NAudio::Wave']]],
  ['impulseresponseconvolution_71',['ImpulseResponseConvolution',['../class_n_audio_1_1_dsp_1_1_impulse_response_convolution.html',1,'NAudio::Dsp']]],
  ['infochunk_72',['InfoChunk',['../class_n_audio_1_1_sound_font_1_1_info_chunk.html',1,'NAudio::SoundFont']]],
  ['infograb_73',['InfoGrab',['../classxeno__rat__server_1_1_forms_1_1_info_grab.html',1,'xeno_rat_server::Forms']]],
  ['input_5fhandler_74',['input_handler',['../class_hidden__handler_1_1input__handler.html',1,'Hidden_handler']]],
  ['inputhandler_75',['InputHandler',['../class_plugin_1_1_input_handler.html',1,'Plugin']]],
  ['instrument_76',['Instrument',['../class_n_audio_1_1_sound_font_1_1_instrument.html',1,'NAudio::SoundFont']]],
  ['ipanstrategy_77',['IPanStrategy',['../interface_n_audio_1_1_wave_1_1_sample_providers_1_1_i_pan_strategy.html',1,'NAudio::Wave::SampleProviders']]],
  ['ipropertystore_78',['IPropertyStore',['../interface_n_audio_1_1_core_audio_api_1_1_interfaces_1_1_i_property_store.html',1,'NAudio::CoreAudioApi::Interfaces']]],
  ['isamplechunkconverter_79',['ISampleChunkConverter',['../interface_n_audio_1_1_wave_1_1_sample_providers_1_1_i_sample_chunk_converter.html',1,'NAudio::Wave::SampleProviders']]],
  ['isamplenotifier_80',['ISampleNotifier',['../interface_n_audio_1_1_wave_1_1_i_sample_notifier.html',1,'NAudio::Wave']]],
  ['isampleprovider_81',['ISampleProvider',['../interface_n_audio_1_1_wave_1_1_i_sample_provider.html',1,'NAudio::Wave']]],
  ['iserviceprovider_82',['IServiceProvider',['../interface_plugin_1_1_system_utility_1_1_i_service_provider.html',1,'Plugin::SystemUtility']]],
  ['ishellbrowser_83',['IShellBrowser',['../interface_plugin_1_1_system_utility_1_1_i_shell_browser.html',1,'Plugin::SystemUtility']]],
  ['ishelldispatch2_84',['IShellDispatch2',['../interface_plugin_1_1_system_utility_1_1_i_shell_dispatch2.html',1,'Plugin::SystemUtility']]],
  ['ishellfolderviewdual_85',['IShellFolderViewDual',['../interface_plugin_1_1_system_utility_1_1_i_shell_folder_view_dual.html',1,'Plugin::SystemUtility']]],
  ['ishellview_86',['IShellView',['../interface_plugin_1_1_system_utility_1_1_i_shell_view.html',1,'Plugin::SystemUtility']]],
  ['ishellwindows_87',['IShellWindows',['../interface_plugin_1_1_system_utility_1_1_i_shell_windows.html',1,'Plugin::SystemUtility']]],
  ['istream_88',['IStream',['../class_i_stream.html',1,'']]],
  ['ivideosource_89',['IVideoSource',['../interface_a_forge_1_1_video_1_1_i_video_source.html',1,'AForge::Video']]],
  ['iwavebuffer_90',['IWaveBuffer',['../interface_n_audio_1_1_wave_1_1_i_wave_buffer.html',1,'NAudio::Wave']]],
  ['iwavein_91',['IWaveIn',['../interface_n_audio_1_1_wave_1_1_i_wave_in.html',1,'NAudio::Wave']]],
  ['iwaveplayer_92',['IWavePlayer',['../interface_n_audio_1_1_wave_1_1_i_wave_player.html',1,'NAudio::Wave']]],
  ['iwaveposition_93',['IWavePosition',['../interface_n_audio_1_1_wave_1_1_i_wave_position.html',1,'NAudio::Wave']]],
  ['iwaveprovider_94',['IWaveProvider',['../interface_n_audio_1_1_wave_1_1_i_wave_provider.html',1,'NAudio::Wave']]],
  ['iwmresamplerprops_95',['IWMResamplerProps',['../interface_n_audio_1_1_dmo_1_1_i_w_m_resampler_props.html',1,'NAudio::Dmo']]]
];
